### ISSUE TITLE
Challenges implementing Multi-Value Control

### ISSUE THREAD

**Issue by jprettyman** [Microsoft/vsts-extension-multivalue-control#10]
I am struggling to get the Multi-Value control to display in the Web Page. I have done all that I have thought is needed, but it does not work.

I have attached an XML with what I have done but it does not work. I am attempting to set the Target Version Fields as a Multi-value Field.
[Product Backlog Item.xml.txt](https://github.com/Microsoft/vsts-extension-multivalue-control/files/680165/Product.Backlog.Item.xml.txt)

**Comment by mmanela** [comment]
A few questions for you
1. Are you on VSTS or TFS?
2. If TFS, which version are you on?
3.  Do you have the New work item form enabled? (These extensions are only for the new work item form)

**Comment by jprettyman** [comment]
Matthew,


Item number three was the correct answer. I was not aware of this setting. I have activated the new forms and now it works.


Thank you for your reply. This helped tremendously.


Joe Phy


________________________________
