### ISSUE TITLE
How do i generate the dist folder?

### ISSUE THREAD

**Issue by dariusneo** [microsoft/vsts-extension-multivalue-control#100]
Hi after i have clone this project, how do i generate the dist folder?  as i seen in the vss-extension.json there's a path pointing to dist
    "files": [
        {
            "path": "dist",
            "addressable": true
        },

**Comment by dariusneo** [comment]
hi is there a way to import the inputs value from vss-extension.json from multivalue.html without using typescript but using javascript?

**Comment by mmanela** [comment]
What do you mean? Can you elaborate?

**Comment by madkoo** [comment]
The way this extension is packaged has changed with the new release due do that this issue is no longer valid. Closing this issue, feel free to create a new issue if you have problems
