### ISSUE TITLE
Multivalue control by Microsoft DevLabs failed to load.

### ISSUE THREAD

**Issue by mishellcap** [Microsoft/vsts-extension-multivalue-control#101]
Some of the guest users to our Azure DevOps Services ("cloud") organization are coming across the below error when trying to load a work item type that contains the custom Multivalue control. 

The error message they are receiving is, "Multivalue control by Microsoft DevLabs failed to load."

Our internal users and other guest users have not been able to reproduce this issue. Guest users are users who are guest accounts on the Azure Active Directory our DevOps collection is connected to.

**Any troubleshooting steps for this issue, along with common reasons why the multivalue control fails to load, would be _much_ appreciated!** 

We've had the guest users try multiple different browsers (Edge, IE, Chrome, and Firefox), InPrivate browsing mode, and clearing all browser data to no avail.

![failed to load](https://user-images.githubusercontent.com/20054901/52418868-f5594f80-2abc-11e9-968d-c270de52d76b.png)

**Comment by trevorsg** [comment]
If it is the same issue, it's in the deployment pipeline right now. Should be live soon.

**Comment by mishellcap** [comment]
Thank you for the quick reply, @mmanela and @trevorsg ! I will reply back with some screenshot(s) from the users.

**Comment by mishellcap** [comment]
Hi, the users came back and said that the issue has been resolved on their end. It turned out the issue was caused by settings on their VLAN. 

Local IT resolution: “(/|\.|^)vsassets\.io has been added for mentioned VLAN.”

Thank you again for the quick replies. Closing out this issue.
