### ISSUE TITLE
Multivalue Control Not behaving as expected

### ISSUE THREAD

**Issue by KirkSonnier** [microsoft/vsts-extension-multivalue-control#103]
1. Open a work item and update the multivalue control until there are 2 or more rows of values.
![image](https://user-images.githubusercontent.com/49252747/55511077-6586dc00-55fb-11e9-998f-e23f58510450.png)
2. Make a change to a field on a different page and click Save.
![image](https://user-images.githubusercontent.com/49252747/55511282-e514ab00-55fb-11e9-93ce-e2fc31db3bb3.png)
3. Go back to the first page and observe the multivalue control doesn't show all of the values and can't be updated unless one of the values is removed or the work item refresh button is clicked.
![image](https://user-images.githubusercontent.com/49252747/55511410-40df3400-55fc-11e9-8414-9e76de3930eb.png)

**Comment by madkoo** [comment]
This is fixed with the latest release. Closing the issue for now. Feel free to create a new issue if the issue persists.
