### ISSUE TITLE
vsts-extensions-multivalue-control by ms-devlabs failed to load with message in cosole "Blocked loading mixed active content"

### ISSUE THREAD

**Issue by aristocrat-vijay** [microsoft/vsts-extension-multivalue-control#104]
Blocked loading mixed active content “http://xxx/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/vsts-extensions-multivalue-control/2.2.25/assetbyname/dist/multivalue.html” @ @

**Comment by aristocrat-vijay** [comment]
![image](https://user-images.githubusercontent.com/33393399/55550102-12914f80-56f5-11e9-93cb-dfde31c3d276.png)

**Comment by mmanela** [comment]
What is the public url that you configured for your server? Is it set to HTTPS or HTTP?

**Comment by aristocrat-vijay** [comment]
> 
> 
> What is the public url that you configured for your server? Is it set to HTTPS or HTTP?

Its configured with https --> "https://xxx.com/tfs/DefaultCollection/" and users can connect to it after connecting VPN network.

**Comment by mmanela** [comment]
Is that what you have configured in the admin console? 

What do you see on this screen on yours?
![image](https://user-images.githubusercontent.com/304410/56854071-ab2a8200-68e5-11e9-84ec-601d1ad3281e.png)

**Comment by pguerre** [comment]
I am also seeing this issue and my public URL is configured in the admin console. We only have one application tier
![tempsnip](https://user-images.githubusercontent.com/31321932/61059494-13f2a800-a3c7-11e9-9b8c-b489ef744de3.png)

**Comment by pguerre** [comment]
is there any update for this?

**Comment by okochet** [comment]
We also use TFS on premises 2018 Update 3 and could see the same issue. Do we have a workaround for it?
