### ISSUE TITLE
Requires "Allow users to enter their own values" be enabled.

### ISSUE THREAD

**Issue by spellacl** [microsoft/vsts-extension-multivalue-control#105]
Use of the extension requires "Allow users to enter their own values" be enabled for the field when field type is "Picklist (string)". Otherwise, input example such as "Windows; Linux; etc" is interpreted as a user-defined input, not an option from the picklist(String).

**Comment by mmanela** [comment]
You should use this extension with a multi-line text field and not a pick list field
