### ISSUE TITLE
The value of the field is too long

### ISSUE THREAD

**Issue by mbendtsen** [microsoft/vsts-extension-multivalue-control#107]
Getting an error that the value of the field is too long. What is the max length? Is this a bug or can I do something to fix it?

### Field Definition:
```
<FIELD name="Products" refname="Sonlinc.Products" type="String" reportable="dimension">
  <SUGGESTEDVALUES expanditems="true">
    <GLOBALLIST name="Sonlinc.Products" />
  </SUGGESTEDVALUES>
</FIELD>
```

### WebLayout:
```
<ControlContribution Label="Products" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
  <Inputs>
    <Input Id="FieldName" Value="Sonlinc.Products" />
  </Inputs>
</ControlContribution>
```

### Error description:
![value too long](https://user-images.githubusercontent.com/338354/58553374-1634e480-8215-11e9-8441-f2e5c2ddca41.png)

**Comment by mmanela** [comment]
To support longer values you should use a field with type PlainText  instead.

**Comment by bcarthic** [comment]
For single line text field and one of the value of the picklist field, the max length is 255.
