### ISSUE TITLE
Remove the "Select All"  with TFS 2018 

### ISSUE THREAD

**Issue by VolicTV** [microsoft/vsts-extension-multivalue-control#109]
I am trying to remove the select all feature in TFS 2018.  It is not in the global list, so I'm not sure where I can remove it. I saw how to do it in Azure devops, but not a way to do it through the XML form.

**Comment by prashanthbv12** [comment]
In Azure Devops services we are using it as a single value checkbox in some cases. Is it possible to customize Select All to keep if we need for specific fields?

**Comment by AminTi** [comment]
Hi!,  please let me know if you till having the same issue
