### ISSUE TITLE
getSuggestedValues is not returning correct values

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/vsts-extension-multivalue-control#110]
service.getAllowedFieldValues() is not returning correct values. 

I see that it is including deleted values or values from a different wit which is not expected. I see that the target API call is resolving to:
https://dev.azure.com/{organization}/_api/_wit/allowedValues?__v=5&projectId={projectId}&workItemTypeName={workitemtype}&fieldRefName={fieldReference}&fieldId={fieldId}

But I am seeing the right values when I query the field to check the allowed values using API:
https://dev.azure.com/{organization}/{projectId}/_apis/wit/workitemtypes/{workitemtype}/fields/{fieldReference}?$expand=all

**Comment by sunahe** [comment]
Same issue in when using the extension in Azure DevOps Server (2019.1)

**Comment by StephenRSkinner** [comment]
Is this the same issue as #121 and #130 ? If so, it would appear this has been a known issue for over a year. When will it be corrected so we can use this control again?

**Comment by AminTi** [comment]
Hi!,  please let me know if you till having the same issue
