### ISSUE TITLE
Control not loading in all browsers

### ISSUE THREAD

**Issue by cverdow** [microsoft/vsts-extension-multivalue-control#114]
The control was loading correctly last week.  It will now not load in Google Chrome.  It does load in Internet Explorer.

**Comment by cverdow** [comment]
multivalue.js:21 Uncaught (in promise) Objectmessage: "n.forEach is not a function"name: "TypeError"stack: "TypeError: n.forEach is not a function↵    at https://cdn.vsassets.io/bundles/vss-bundle-async-vgrBFOTCnCQbqogxx_eDjPQBMql065ZSL-B4-Nb6M6U0=:9:5942"__proto__: Object

**Comment by nickbrooking** [comment]
Same issue here as well.

**Comment by v-yanfga** [comment]
I met the same issue today, Control is missing in Edge, but there is no issue in IE browser, when page first load in Google Chrome, on issue occurred, but then try reload the page I've got below exception:
![image](https://user-images.githubusercontent.com/42028535/61684791-236ddb80-ad4d-11e9-8194-64e4fa123b39.png)

**Comment by benedikt-goeppner** [comment]
Same issue here

**Comment by willignicolas** [comment]
Same issue here. We reset cookie and it works one time. But same problem after.

Thanks for your help

**Comment by nickbrooking** [comment]
If I change something in the work item process settings, such as add or remove a field, it shows up for one refresh as well, then breaks again.

**Comment by nickbrooking** [comment]
This is not just Chrome by the way, it behaves the same in all browsers including IE.

**Comment by cverdow** [comment]
Confirmed I am seeing it in all browsers.  It just happened to work once in IE.

**Comment by mohitbagra** [comment]
Thanks for letting us know. It doesnt look like an issue in the extension since we havent changed anything in it lately. So it looks like a bug in Azure devops product code. We are investigating and will send an update and an ETA for the fix soon

**Comment by mohitbagra** [comment]
The issue should be fixed now.

**Comment by mohitbagra** [comment]
Can anyone verify?

**Comment by cverdow** [comment]
It is now fixed for me.  Thank you!

**Comment by nickbrooking** [comment]
Working for us as well.

**Comment by mohitbagra** [comment]
Thanks. Closing the issue.
