### ISSUE TITLE
Textbox not displayed straight away when creating new WIT

### ISSUE THREAD

**Issue by DinaS04** [microsoft/vsts-extension-multivalue-control#115]
Steps to reproduce:
1. Create two new string fields in a WIT and use the multi-value control to display them.
2. Create a new WIT from that type.
3. Look at these string fields.

Result:
The text boxes are not displayed at first:
![image](https://user-images.githubusercontent.com/53757821/62459700-c03a6b00-b788-11e9-82ef-c2eec81545c5.png)

After a while they appear:
![image](https://user-images.githubusercontent.com/53757821/62459618-8d907280-b788-11e9-84e1-6fe70f60a944.png)

**Comment by obvioussean** [comment]
The multivalue control is loaded asynchronously.  You should see a spinner while it is loading do you not?  And how long is the delay?  The more extensions on the form the longer it takes to load them.

**Comment by DinaS04** [comment]
The spinner loads for about 3 seconds and afterwards it takes another 5 seconds to load.
We have to multi value fields in the section. We work with Chrome

**Comment by DinaS04** [comment]
We have TFS 2018 update 2 installed.

Edge shows the same latency.

IE doesn’t have any delay.

**Comment by DinaS04** [comment]
> We have TFS 2018 update 2 installed.
> 
> Edge shows the same latency.
> 
> IE doesn’t have any delay.

 Can someone assist?

**Comment by AminTi** [comment]
Hi!,  please let me know if you still have the same issue
