### ISSUE TITLE
Multivalue control has stopped wrking in my test environment.

### ISSUE THREAD

**Issue by patdelaney** [microsoft/vsts-extension-multivalue-control#117]
We are on TFS 2018 update 3.2 and in my test environment the control has stopped working. When I open a page that has the control I get 
Multivalue control by Microsoft DevLabs failed to load.Learn More about this extension, including available support options.

Is there any logging on can turn on to see what the error really is?

**Comment by patdelaney** [comment]
I can't seem to add a screenshot

**Comment by patdelaney** [comment]
![image](https://user-images.githubusercontent.com/8147459/65877380-27bc0380-e351-11e9-959b-daa0cc0b0b82.png)
Any update on this?

**Comment by obvioussean** [comment]
Do you see any errors in the javascript console?

**Comment by patdelaney** [comment]
I'm not familiar with the Javascript console


Pat

**Comment by obvioussean** [comment]
In most browsers you can hit the F12 function key and it opens a new window which includes the javascript console.  In that you should be able to see the error if you reload the page.

**Comment by patdelaney** [comment]
OK I will chekc in the am when I get to the office.  Thanks for helping out

**Comment by patdelaney** [comment]
I went to test again today, I added the definition for the control back in
the WIT and it's working again.  That's odd.

I removed it yesterday so I could do some other testing, I added it back
and now it's working fine.

I guess we can close the issue for now.

Thanks

**Comment by patdelaney** [comment]
It appears to be broken again. Here are the errors in the console:
wps-tfsapp-t01:8080/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/vsts-extensions-multivalue-control/2.2.25/assetbyname/dist/multivalue.html:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

main.js:42 in Startnull

Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:114 null

(anonymous) @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:114

(anonymous) @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:114

c @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

(anonymous) @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

u.promiseDispatch @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

(anonymous) @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

t @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

main.js:42 in Startnull

main.js:42 in Startnull

main.js:42 in Startnull

main.js:42 in Startnull

Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:38 (no stack) null

(anonymous) @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:38

t @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:38

setTimeout (async)

t @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:38

setTimeout (async)

t @ Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:38

Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:38 Error: Cannot get registered instance for : ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control

    at Content?bundle=vss-bundle-async-vzSSPbubgvVasb-tgPD1k4aykofJG_jhjqDVZdXiIOr4=:74

    at l (Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28)

    at Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

    at t.when (Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28)

    at t.u.promiseDispatch (Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28)

    at Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28

    at MessagePort.t (Content?bundle=vss-bundle-common-v8M9zqW9MNbh12jJ2b_fKK5bP3crVXrw2L6xrxNDfyVg=:28)

**Comment by obvioussean** [comment]
Ok, I need to know what that bad request is.  In Chrome you can export the network requests, could you please do that?

![image](https://user-images.githubusercontent.com/15038374/66063168-af437700-e4f7-11e9-9b81-0cb0b9c90fe2.png)

**Comment by patdelaney** [comment]
And it's working again today ... so the next time it breaks I'll get the info.  This is wierd.

**Comment by patdelaney** [comment]
And it's broken again today  
[tfsapp-t01.zip](https://github.com/microsoft/vsts-extension-multivalue-control/files/3870752/tfsapp-t01.zip)
:-(

**Comment by formeroosid** [comment]
We upgraded to TFS 2018 over the weekend and we are consistently seeing this error. 

![2020-04-13_15-38-45](https://user-images.githubusercontent.com/5659343/79167708-f068ed80-7d9c-11ea-8047-dc382e642b78.jpg)
![Console](https://user-images.githubusercontent.com/5659343/79167715-f6f76500-7d9c-11ea-94b5-41e54cbdd87b.jpg)

I have an network export form the browser developer tools, but I'd rather not post it publicly. How can I get this to you? 

Jamie

**Comment by dabrantkosky** [comment]
Same problem, but with just a few users and its intermittent on IE and Edge.
