### ISSUE TITLE
Can not uninstall it 

### ISSUE THREAD

**Issue by gordingin** [microsoft/vsts-extension-multivalue-control#119]
I installed this control and it didn't behave as expected. I just wanted to add custom values of anything to my user stories.

So I tried to uninstall it  and now I get this on ALL of my user stories.

![image](https://user-images.githubusercontent.com/6098691/64076201-ca6c5e00-cc8f-11e9-9cce-fd34ef51e95e.png)

**Comment by obvioussean** [comment]
Followed up with @gordingin on a different thread, this was a process template issue.
