### ISSUE TITLE
The strings are truncated

### ISSUE THREAD

**Issue by allagerman** [Microsoft/vsts-extension-multivalue-control#12]
Hello,
Thanks for the extension. Its helps a lot!
We have long strings as options for multi-select control and they look truncated from UI when we select them. Is there any way to control the control width from XML?
![image](https://cloud.githubusercontent.com/assets/25645881/22753597/7f591cac-edf1-11e6-9388-1f1ba2805450.png)
Thanks,
Alla

**Comment by cschleiden** [comment]
Width is determined by the work item form layout. Can you move the control to another (i.e. wider) column in your layout?

**Comment by allagerman** [comment]
Here is how the entire page looks from UI
![image](https://cloud.githubusercontent.com/assets/25645881/22754936/fad45cf8-edf5-11e6-89c8-ccdad15d0df1.png)
and  from XML
        <Page Label="Announcements" LayoutMode="EqualColumns">
          <Section>
            <Group Label="Publication Actions">
              <Control Label="Public Roadmap" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.PublicRoadmap" />
              <Control Label="Public Rdmp Status" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.PublicRdmpStatus" />
              <Control Label="Rdmp Live Date" Type="DateTimeControl" FieldName="RDX.ETS.Change.Roadmap.RdmpLiveDate" />
              <Control Label="NDA Newsletter" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.NDANewsletter" />
              <Control Label="Newslt Live Date" Type="DateTimeControl" FieldName="RDX.ETS.Change.Roadmap.NewsltLiveDate" />
              <Control Label="O365 Blog" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.O365Blog" />
              <Control Label="App Blog" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.AppBlog" />
              <Control Label="Publishing Notes" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.PublishingNotes" />
              <Control Label="PMG Approved" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.PMGApproved" />
            </Group>
            <Group Label="Public Information">
              <Control Label="Public Title" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.PublicTitle" />
            </Group>
            <Group Label="Public Description">
              <Control Label="Final App Store Description" Type="HtmlFieldControl" FieldName="RDX.ETS.Change.Roadmap.PublicDescription" />
            </Group>
            <Group Label="">
              <Control Label="URL" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.URL" />
            </Group>
          </Section>
          <Section>
            <Group Label="Engineering Communication Plans">
              <Control Label="Pillars" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.EngCommPlans.Pillars" />
              <Control Label="SLT" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.EngCommPlans.SLT" />
              <Control Label="MPR" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.EngCommPlans.MPR" />
              <Control Label="Others (Specify)" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.EngCommPlans.Others" />
              <Control Label="ONELIST ID" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.EngCommPlans.OneListId" />
            </Group>
            <Group Label="Marketing Plans">
              <Control Label="Announcement Tier" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.MarketingPlans.AnnouncementTier" />
              <Control Label="Announcement Date" Type="DateTimeControl" FieldName="RDX.ETS.Change.Roadmap.MarketingPlans.AnnouncementDate" />
              <Control Label="Consumer/Commercial" Type="FieldControl" FieldName="RDX.ETS.Change.Roadmap.MarketingPlans.ConsumerCommercial" />
              <ControlContribution Label="Moments" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
                <Inputs>
                  <Input Id="FieldName" Value="RDX.ETS.Change.Roadmap.MarketingPlans.Moments" />
                </Inputs>
              </ControlContribution>
              <ControlContribution Label="SKU" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
                <Inputs>
                  <Input Id="FieldName" Value="RDX.ETS.Change.Roadmap.MarketingPlans.SKU" />
                </Inputs>
              </ControlContribution>
              <ControlContribution Label="Cloud Instance" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
                <Inputs>
                  <Input Id="FieldName" Value="RDX.ETS.Change.Roadmap.MarketingPlans.CloudInstance" />
                </Inputs>
              </ControlContribution>
            </Group>
          </Section>
        </Page>

2 sections have equal width. and "SKU" control takes 100% of the section, however inside the control each option doesn't have the full width
![image](https://cloud.githubusercontent.com/assets/25645881/22755021/4c09d06c-edf6-11e6-839b-47a2c618e746.png)

**Comment by mmanela** [comment]
Thanks @allagerman for reporting this bug. @mohitbagra or @ostreifel, can one of you take a look at this?

**Comment by ostreifel** [comment]
pr #14
