### ISSUE TITLE
Multivalue control has stopped working in my test environment

### ISSUE THREAD

**Issue by patdelaney** [microsoft/vsts-extension-multivalue-control#125]
It's broken again today, It was working earlier. Here is the log. This is related to 117. (Same)

[tfsapp-t01.zip](https://github.com/microsoft/vsts-extension-multivalue-control/files/3870766/tfsapp-t01.zip)

**Comment by patdelaney** [comment]
Any WIT that has Multivalue in it is broken. It's not limited to just one Project/Wit

**Comment by obvioussean** [comment]
Can you please provide the console output?

**Comment by obvioussean** [comment]
Actually, looking at the HAR it seems to be using the URL for the local version of your server.  You need to ensure your public access mapping is correctly configured for the multivalue control to work.

**Comment by patdelaney** [comment]
I thought I attached it to the ticket as a zip file

**Comment by patdelaney** [comment]
I',mnot sure what you are saying, How to I fix that in the control?

**Comment by patdelaney** [comment]
I checked my test environment and the control is working again. I can't for the live of me figure out why it comes and goes. I have not modified the WIT that it is using.

**Comment by obvioussean** [comment]
The zip had the har, which does not include console output.  But in this case the issue isn't with the control, it's with how you've configured your public access mapping.  Did you verify that it is correct?

**Comment by patdelaney** [comment]
The control was working again this morning and I have changed nothing on
the Server.

I'm not sure where you check or set  the public address mapping.  We are on
TFS 2018 update 3.2

Pat

**Comment by obvioussean** [comment]
It’s configured in the tfsmgmt tool.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by patdelaney** [comment]
I'll get a screenshot on Monday

**Comment by Xenimus** [comment]
I am seeing the same issue, my Multivalue Control extension seemingly stopped working randomly too. Importing work items presents the error: VS403121: Extension(s) "ms-devlabs.vsts-extensions-multivalue-control" does not exist , or has no work item form contribution. 

Is the fix to ensure your public access mapping is correctly configured for the multivalue control to work?

**Comment by bgordon99** [comment]
I am seeing this issue as well with our on prem test environment. Has happened twice now. Happens in Chrome, IE, Edge. Deleting temp files, etc. has no effect. There were no changes to environment and no changes to the WIT. Just stopped working. I don't think the public access mapping is the issue because it worked for a time with the same settings.

**Comment by patdelaney** [comment]
I noticed that this happened again

**Comment by patdelaney** [comment]
It was not working again this morning, if I log onto the server and run iisreset /restart it works again. While this is a workaround for my test environment. This is not acceptable for production.  I am no the only person reporting this behavior.  Please leverage those of us with the issue to gather information to get to the route cause of the problem.

I will kick this off with questions that may make it easier for me to troubleshoot.

Do the current plugin have any sort of auto updating feature, where maybe it's trying to access the internet to check its version to see if it should be updated?

When you open a workitem that contains a field that uses the multi-select you know it's going to error when you get a spinning loading icon (in chrome) near the field that has that control.

Does the multivalue control access and sort of running process on the server when loading? or is all the functionality of the plugin handled by the browser? And if that is the case why does IISRESET / restart on the TFS app server fix the issue?

Here are the lines in my workitem that are related to the control.

the definition of the field:
      **<FIELD name="Region" refname="WPS.Bug.Region" type="String" reportable="dimension">
        <REQUIRED />
        <SUGGESTEDVALUES expanditems="true">
          <LISTITEM value="[East]" />
          <LISTITEM value="[OS]" />
          <LISTITEM value="[TDEFIC]" />
        </SUGGESTEDVALUES>
      </FIELD>**

The section for how it's displayed in Visual Studio
                    **<Control FieldName="WPS.Bug.Region" Type="MultiValueControl" Label="Region" LabelPosition="Left">
                      <CustomControlOptions />
                    </Control>**

The definition of the extension at the top of the web layout
        **<Extensions>
          <Extension Id="ms-devlabs.vsts-extensions-multivalue-control" />
        </Extensions>**

The section in Web Layout for the field
            <Group Label="Classification">
              <Control Label="Value area" Type="FieldControl" FieldName="Microsoft.VSTS.Common.ValueArea" />
              **<ControlContribution Label="Region" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
                <Inputs>
                  <Input Id="FieldName" Value="WPS.Bug.Region" />
                </Inputs>
              </ControlContribution>**
            </Group>
