### ISSUE TITLE
User-entered values always render and store in lower case

### ISSUE THREAD

**Issue by qJake** [microsoft/vsts-extension-multivalue-control#128]
When users are allowed to enter their own values, the casing of the selection is not preserved. Instead, lowercase is forced.

![image](https://user-images.githubusercontent.com/652006/69742601-adb2bb80-1102-11ea-8fd6-55f8b72bb1f8.png)

We use this control for clients (for which we have acronyms), so it's important that the casing be maintained during user input. The client should be listed as "ABC", not "abc".

**Comment by randomuser369** [comment]
I just tried to report this as a bug in the Azure DevOps feedback portal and they referred me to here.

https://developercommunity.visualstudio.com/t/multivalue-control-ignores-case-sensitivity/1528266?from=email
