### ISSUE TITLE
Dropdown disappears on clicking selection in Firefox on Mac

### ISSUE THREAD

**Issue by seanknox** [microsoft/vsts-extension-multivalue-control#131]
Running Firefox 72.0.2 (64-bit) on Mac.

Same issue as https://github.com/microsoft/vsts-extension-multivalue-control/issues/129. Attempting to select any option doesn't select and closes the dropdown. Works on Chrome on a Mac and Edge on Windows. 

![out](https://user-images.githubusercontent.com/1231630/73316835-17c20c80-41e9-11ea-8939-76ae3cd9250f.gif)

**Comment by AminTi** [comment]
This issue should be fixed
