### ISSUE TITLE
Change values programmatically

### ISSUE THREAD

**Issue by maurizioprazzoli** [microsoft/vsts-extension-multivalue-control#132]
Thank you very much for this great control :-)

We'd like to be able to update the suggested values programmatically insted of insert them manually from the Otpion section. Could you kindly provide me some insights to perform this operation?

Thank you very much

**Comment by Dedac** [comment]
If you can use a string picklist (not always the case) you can update that from the Azure DevOps Api
https://docs.microsoft.com/en-us/rest/api/azure/devops/processes/lists?view=azure-devops-rest-5.1

**Comment by madkoo** [comment]
Closing this issue as it has been answered and there has been no feedback.
