### ISSUE TITLE
Readonly parameter can be pypasses wi to multivalue control

### ISSUE THREAD

**Issue by Christ0phH** [microsoft/vsts-extension-multivalue-control#133]
System:
 -Azure DevOps Server 2019.1.1 (Version Dev17.M153.5)
Using
- Chrome  80.0.3987.122
 -FireFox 68.5.0esr
- Multivalue control 2.2.26 (Latest)

When using the xml based control contribution

```
<ControlContribution Label="Somemultivalues label" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
                <Inputs>
                  <Input Id="FieldName" Value="Somemultivalues" />
                </Inputs>			
</ControlContribution>
```

and defining a readonly state e.g. in a state definition or transition

```
<FIELD refname="Somemultivalues" >
	<READONLY for="[Project]\AUserGroup"/>	  	  
</FIELD>
```

**

- The field still can be changed by the "AUserGroup"
- The error message "The value for field 'Somemultivalues' must be the same as the original value." is displayed when picking something more and other then the former value
- ! But when picking NOTHING saving the change by "AUserGroup" is possible!
-- Parameter "CANNOTLOSEVALUE" is not helping

**

**Comment by AminTi** [comment]
We will review and close old issues that have been resolved or no longer require attention. If you still experience any problems or have further questions, please do not hesitate to contact us
