### ISSUE TITLE
Multivalue Control not displaying on form properly

### ISSUE THREAD

**Issue by ssteiner1** [microsoft/vsts-extension-multivalue-control#135]
Multivalue control enabled for picklist.  Both the control extension and field have "Allow users to enter custom values".   User selects multiple values from picklist and saves work item.  Multivalue control field flashes the selections, then clears them out, so field displays as blank.  However, the values show in the History of work item as well as in the grid.  

[MultiValueControlIssue.docx](https://github.com/microsoft/vsts-extension-multivalue-control/files/4488880/MultiValueControlIssue.docx)

**Comment by madkoo** [comment]
This issue should be resolved with the latest release. Closing this issue for now. Feel free to reopen if the problem still persists
