### ISSUE TITLE
Number of allowed items 

### ISSUE THREAD

**Issue by OtakarS** [microsoft/vsts-extension-multivalue-control#138]
Hi, What is the max number allowed in multi value? My team would like to be able to select more than 10 items. Is this possible, please?

**Comment by Dedac** [comment]
If you use a bigger backing field, like the multi-line text, you can select more values.  It does mean that you have to put the list of selectable items in the custom control, instead of using the values in an existing picklist though.

**Comment by madkoo** [comment]
Closing this issue as this has been answered and no further feedback is provided.
