### ISSUE TITLE
Unable to remove Mutlivalue Control from a work item

### ISSUE THREAD

**Issue by tywncoch** [microsoft/vsts-extension-multivalue-control#139]
In Azure Devops I added the Multivalue Control to a Bug work item type using an existing Picklist (string) field.

The control appears to add the field twice on the work item, once for the Multivalue Control and once for the Picklist field. 

I then tried to remove the Control and Picklist Field from the Bug layout and nothing happens. Both remain.

**Comment by Dedac** [comment]
I ran into a similar issue and it was solved by refreshing the page.  Not ideal, but it worked for me.

**Comment by madkoo** [comment]
Closing this issue as no further feedback has been provided. If the problem still persists feel free to create a new issue
