### ISSUE TITLE
MultiValue Control suddenly failing in one DevOps Organisation

### ISSUE THREAD

**Issue by ChrisZoey** [microsoft/vsts-extension-multivalue-control#141]
Help!
I am using the MultiValue Control extension (by Microsoft DevLabs) in a workitem in Azure DevOps Services (cloud). It's been working nicely for over a year. Suddenly the control has 'failed to load' or 'is taking longer than expected', since c.Fri 19/06/20.

I am running IE11 and Win7 environment with no option to change the browser (controlled by central IT Admin). I have a number of test organisations but all of our key projects are managed in one key DevOps Organisation. 

What's the issue?
- The control fails in the key DevOps Organisation. I uninstalled/reinstalled it, to no avail. It just seems to fail in that particular Organisation.

What works?
- The control works in another test DevOps Organisation within my tenant, in the same IE11/Win7 environment. I added the control to a new test Organisation ... it works there!
- The control works on my phone. I tested the control in the production Organisation using my Android phone. It works there!
- The control works in IE11/Win10.

I need the control to continue working in my key DevOps Organisation?
Can someone please guide me on this?
Thank you in advance,
     Chris

**Comment by ChrisZoey** [comment]
[Closing] Eventually I got Chromium Edge installed in Win7. Works a treat, as I'd hoped. I'll put my original issue (described above) down to IE11 compatibility issues. But I'd still love to know what happened! Must be impacting others out there.

**Comment by AminTi** [comment]
Hi!,  please let me know if you still have the same issue
