### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by aadrinic** [microsoft/vsts-extension-multivalue-control#144]
I keep getting this message "The field 'Activity' contains the value ' CFE; FBI/CORP FIN; OTHER' that is not in the list of supported values." 

After deleting all the data assigned I was able to clear the message... any idea why this was coming up? Is there a new update or particular way I should word things? Was working perfectly before & even yesterday I didn't get this message.

**Comment by AminTi** [comment]
Hi!,  please let me know if you still have the same issue.
