### ISSUE TITLE
"Remove from Layout" warning given when attempting to add a new value to the Drop-down

### ISSUE THREAD

**Issue by dkelchne** [microsoft/vsts-extension-multivalue-control#156]
I'm trying to add a new value to a field which uses the multivalue control and after I press "+Add value" and then "Save" I get a warning asking if I am sure I want to remove the required field from the layout.
![image](https://user-images.githubusercontent.com/60367294/103910410-ca297180-50d2-11eb-8102-20e4352734b9.png)

**Comment by MarRich1** [comment]
Is there already a solution for this issue?
I´ve the same problem. Could it maybe related to the number of items?

**Comment by MarRich1** [comment]
After setting a default value I was able to add an additional item. And the message didn´t appeared anymore when I cleared the default value again

**Comment by madkoo** [comment]
@marRich1 happy to hear you got it to work.
