### ISSUE TITLE
multivalue-control menu opens behind workitem window

### ISSUE THREAD

**Issue by icnaan** [Microsoft/vsts-extension-multivalue-control#16]
Hi

I have TFS 2017 update 1 and I have installed version 1.0.5. of the control
I have a field populated with  SUGGESTEDVALUES just like I used to do in TFS 2015 
but the menu (after looking for it...)  seems to open **under** the workitem window
I have tried chrome , chrome incognito window and IE ... all behave the same (under windows 10).

see attached screen capture for more details 

![image](https://cloud.githubusercontent.com/assets/26790499/24498992/f12dd04c-1548-11e7-8553-0c9ea054310e.png)

![image](https://cloud.githubusercontent.com/assets/26790499/24498962/d7796eea-1548-11e7-8fc1-17c59cd28bef.png)

**Comment by mmanela** [comment]
@icnaan The screen shot you show does not look like this multi value control. This is what it looks like:
![image](https://cloud.githubusercontent.com/assets/304410/24523053/a1b77826-1546-11e7-9223-e1b1c0f8d224.png)
