### ISSUE TITLE
Is it possible to select multiple values and NOT have to allow users to enter their own values?

### ISSUE THREAD

**Issue by rajanimail1** [microsoft/vsts-extension-multivalue-control#160]
Hello team,

Is it possible to select multiple values and NOT have to allow users to enter their own values?
I see below issue while selecting multiple values if I used picklist instead of text field and NOT select allow users to enter their own values.
![image](https://user-images.githubusercontent.com/50970056/109095879-66362900-76d1-11eb-912e-ad70124aa336.png)

Thank you!

**Comment by NorthHighlandNicole** [comment]
Agreed! This defeats the whole purpose of this control. We have a picklist that we simply need to be able to choose multiple options.

**Comment by kkdoug** [comment]
It there any update as to when this issue may be addressed? Any ideas from the group on work-arounds? The only option I have is to create multiple fields with the same picklist as a short-term, but poor, solution.

**Comment by rajanimail1** [comment]
One way I addressed this issue is to create the field using single Text field. Later use the custom control picklist(String) for same (single Text field) that you created and add values. That worked for me. But if you want to use the field in multiple work item templates, you have to add values each time when you add custom control. Hope that helps.
