### ISSUE TITLE
Long picklist values overlap

### ISSUE THREAD

**Issue by programaka** [microsoft/vsts-extension-multivalue-control#162]
Long picklist values overlap:

<img width="332" alt="overlapping issue" src="https://user-images.githubusercontent.com/12563022/111216174-4f2c7d80-8591-11eb-8b2c-3f6abddf2736.png">

We fixed the issue by adding "white-space: nowrap" and also limiting the height so that horizontal scroll is visible:

<img width="788" alt="fix" src="https://user-images.githubusercontent.com/12563022/111221927-5f942680-8598-11eb-88de-f03c5634849f.png">

This is how it looks now with that fix:

![fix2](https://user-images.githubusercontent.com/12563022/111221945-66bb3480-8598-11eb-90dc-c4e4be0bd2e9.gif)

But I think truncating values and showing the full value in a tooltip will also work.

**Comment by mhglenn258** [comment]
Hi there - We're having this same exact issue with long text strings, but I'm unable to update the code in our ADO instance. Is there a published fix with the latest version? Any guidance on helping us get this fix in place would be appreciated!

**Comment by madkoo** [comment]
@programaka  thanks for the suggested fix. It would be appreciated if you would push this fix as a Pull Request so we can improve the extension.

**Comment by programaka** [comment]
@madkoo It looks like this issue has been resolved, possibly by a recent update in Azure DevOps or as part of another fix in this repository. So, I'm not going to push my fix. Long values are now truncated, and you can see the full value in a tooltip, which looks good to me. I will close the issue.

<img width="363" alt="image" src="https://github.com/user-attachments/assets/4ed0be3b-21dc-482a-a486-c6eb52f38062">

**Comment by programaka** [comment]
@madkoo It looks like this issue has been resolved, possibly by a recent update in Azure DevOps or as part of another fix in this repository. So, I'm not going to push my fix. Long values are now truncated, and you can see the full value in a tooltip, which looks good to me. I will close the issue.

<img width="363" alt="image" src="https://github.com/user-attachments/assets/4ed0be3b-21dc-482a-a486-c6eb52f38062">
