### ISSUE TITLE
Cloning repo and self-packaging, custom control fails to load in Workitem

### ISSUE THREAD

**Issue by ancharbo** [microsoft/vsts-extension-multivalue-control#180]
After cloning the repo and packaging myself, this custom control doesn't load within the workitem. (Multivalue control by ancharbo failed to load. Learn More about this extension, including available support options.) Only changes made were the publisher name,  and replacing a defunct category in the vss-extension.json.

The official ms-devlabs published version works fine. Is there a difference between the ms-devlabs published package and the source that lives here on github?

**Comment by MOlausson** [comment]
@ancharbo we'll have to take a look but one difference may be that dependencies have changed since the last release build was over two years ago.

**Comment by madkoo** [comment]
Wit the new version release of the extension, the packaging has changed. Closing this issue as this is no longer valid.
Feel free to create a new issue if you still have problems.
