### ISSUE TITLE
Length limitation in field

### ISSUE THREAD

**Issue by winniewyweng** [microsoft/vsts-extension-multivalue-control#183]
While I put many items in the field, the warning message shows up and save for the page is not allowed. So I was guided to the github page. Is it possible to fix the issue? Or any workaround can be provided?
![image](https://user-images.githubusercontent.com/92980757/138431051-44713e11-d5ac-4147-9acd-8946465cb307.png)

**Comment by MOlausson** [comment]
@winniewyweng then you are on the cloud version of Azure DevOps. How many items do you have in the select list (not the selected items)?

**Comment by winniewyweng** [comment]
@MOlausson 172 items in the list. The critical point of selected item count to hit the limitation is not always the same. So I am wondering it is related to field length instead of item numbers.

**Comment by madkoo** [comment]
Were you able to resolve this issue ?
