### ISSUE TITLE
Unable to add Rule to multivalue control fields in Azure Devops

### ISSUE THREAD

**Issue by PreethaSarsan** [microsoft/vsts-extension-multivalue-control#185]

**Comment by kalyanc2s** [comment]
Hi @PreethaSarsan 

I am using Azure DevOps. The extension seems to work for me with Rules too. 

In below scenario I created a custom control of System Info and made it mandatory during bug creation. 

I use custom Scrum template, I am not sure if that is impacting the outcome. 

![image](https://user-images.githubusercontent.com/111074551/184175724-b5cff9b9-c4b9-402a-9285-4884fba5c589.png)

![image](https://user-images.githubusercontent.com/111074551/184175299-c5dc9c40-5f3b-478d-827d-3117ece92da0.png)

![image](https://user-images.githubusercontent.com/111074551/184175472-e8bde0af-d5d6-4cd9-b68b-60522e9693c4.png)

**Comment by madkoo** [comment]
Hi, this should be resolved with the latest version. Closing the issue for now, feel free to report a new issue if you still have problems.

**Comment by meeranharish** [comment]
The multi value control field can be set mandatory but we can not add rule to the multivalue control field(eg: to make the field conditionally mandatory)
