### ISSUE TITLE
The field 'Zone' contains the value 'Global' that is not in the list of supported values.

### ISSUE THREAD

**Issue by manoel-soares-ext** [microsoft/vsts-extension-multivalue-control#187]
Hello everyone, how are you doing?

I was trying to rise a ticket (production Issue) on azure devops but "m getting this error msg
"The field 'Zone' contains the value 'Global' that is not in the list of supported values."

The configuration seems to be fine, since on monday it was working but now it's broken.

![Sem título](https://user-images.githubusercontent.com/92820817/147119820-077a5070-92ea-4bf6-9923-f974b648e1fa.png)

**Comment by madkoo** [comment]
Hi, this should be resolved with the latest version. Closing the issue for now, feel free to report a new issue if you still have problems.
