### ISSUE TITLE
MS Preview Feature New Boards Hubs issue

### ISSUE THREAD

**Issue by Jonathan-M-Ball** [microsoft/vsts-extension-multivalue-control#189]
with preview feature new boards hubs on this extension will not load or does not have any values in the drop down 

https://devblogs.microsoft.com/devops/azure-boards-ux-modernization-public-preview/

**Comment by madkoo** [comment]
This should be fixed with the latest release. 
Closing this issue for now. Feel free to reopen if the issue still persists.
