### ISSUE TITLE
Multivalue control plugin do not work with Test Plan -Saas

### ISSUE THREAD

**Issue by Sonali77** [microsoft/vsts-extension-multivalue-control#190]
[Multivalue Plugin.docx](https://github.com/microsoft/vsts-extension-multivalue-control/files/7973008/Multivalue.Plugin.docx)
Multivalue control plugin has been installed in Saas. It seems to work fine when we create a new Test cases from Boards but it  does not work in Test Plan. Please have a look.

**Comment by MOlausson** [comment]
@Sonali77 did you get this to work? Can you check which version you are running? This issue should have been resolved in #179.
