### ISSUE TITLE
Multivalue Control Intermittently not loading (TFS 2018)

### ISSUE THREAD

**Issue by jgeorge3081** [microsoft/vsts-extension-multivalue-control#194]
Using TFS 2018 and lately Multivalue Control Intermittently doesnt load with an error of "Multivalue control by microsoft devlabs failed to load"

Troubleshooting steps taken: 
Removed Plugin and installed it again. Increase server resources, confirmed AV and Firewall are not blocking anything. Issue is occurring on all Browsers and very sporadically and I dont see anything in the logs. 

Info:
Server OS: 2016 
TFS Version 2018 Update 3.2

![image](https://user-images.githubusercontent.com/100788804/156401076-b3e0953a-742b-4b49-82f0-b805e0fa351f.png)

**Comment by AminTi** [comment]
i Just tested it and it work as expected
