### ISSUE TITLE
'set the field X to suggested values rather than allowed values' error message although the field is set to suggested values

### ISSUE THREAD

**Issue by howIhatetheseusernames** [microsoft/vsts-extension-multivalue-control#196]
I always get above error message althogh the respective field is not set to allowed values see screen shot

![image](https://user-images.githubusercontent.com/102171640/159522239-39b884c2-a815-4675-ba2a-50711974e961.png)

when I tick the option for 'Allow users to enter their own values' the error message no longer appears although that's exactly the thing this error message was about in the first place and a setting I do not want to be forced to choose

**Comment by madkoo** [comment]
Closing this issue as this has been answered. 
Is the issue still persists feel free to reopen this issue.
