### ISSUE TITLE
"Multi value Control" Extension doesn't allow multi selection for picklist

### ISSUE THREAD

**Issue by valger-vg** [microsoft/vsts-extension-multivalue-control#199]
Hi there, 

I created a picklist and add multi value control based on that list. If I select more than one value I have an error 
The field 'MyField' contains the value **'Value1;Value2'** that is not in the list of supported values.
I found recommendation to use suggested values instead of allowed ones. However I don't understand what it means. Optional semicolon separated list I can't use together with text field since I can't modify it programmatically via API (or I don't know how to do it). So have to use picklist created and modifiable via API but it doesn't allow multi selection.

**Comment by timritzer** [comment]
The backing field for a picklist must be a single value. Thus you either have to allow custom values (and end up with Option1;Option2 as the saved value) OR use a regular text field (and end up with "Option1;Option2" as the saved value)

This control cannot change the underlying schema/data storage which doesn't support multiple saved independent values.

Use contains searches to filter/search downstream as needed.

**Comment by valger-vg** [comment]
Thank you Tim. You pointed to the 'Allow a user to enter custom value'. The issue was that there are two places where this flag can be set: 'Edit control extension' and 'Edit field'. I set it only for first place since was not aware about second one. After setting this flag for the field it started to work fine.
![image](https://user-images.githubusercontent.com/103988817/164622418-42fa7189-fef8-4433-a730-71c761ff2b88.png)

![image](https://user-images.githubusercontent.com/103988817/164621576-0094d8b5-96aa-4b68-bc59-42941cd91180.png)
![image](https://user-images.githubusercontent.com/103988817/164622231-431c8759-7eee-4e91-b6f0-468851d44239.png)
