### ISSUE TITLE
More examples in xmldetails.md please

### ISSUE THREAD

**Issue by ndc** [Microsoft/vsts-extension-multivalue-control#20]
How to configure the input tag is not so clear:

    <Input Id="FieldName" Value="RefNameOfTheField" />

What should I put as `FieldName`?
What about `RefNameOfTheField`?
Suppose I have a custom field called MyNamespace.MyField, do I put this in Id? Then what should I put as Value? FieldControl?
To specify the list of items, whether from a static list or a global list, and whether to allow existing value, still the same as previous version of TFS?

**Comment by FlexiGit** [comment]
The "Id" is the name which identifies the input. This is used in the extension internally. You must not change it.

The ref name of your field is "MyNamespace.MyField".

So your input tag should look like this:
`<Input Id="FieldName" Value="MyNamespace.MyField" />`

The items are taken from the AllowedValues list. So, yes, this is the same as in previous versions.

**Comment by mmanela** [comment]
@FlexiGit  Is correct. This extension defines two inputs ids **FieldName** and **Values**. For FieldName you make the value the reference name of the field. If you only specify this, then the extension will try to use that fieldName to also get the list of values from its Suggested value list. If you also specify values then it will use that list for the values to populate the control
