### ISSUE TITLE
The value for field 'Country Impacted' is too long.

### ISSUE THREAD

**Issue by AlecMcD13** [microsoft/vsts-extension-multivalue-control#200]
Hi, When we are using the multivalue tool what are the limitations? 

After we pick so many field options, it will give us the error "The value for field 'Country Impacted' is too long." However, I cant seem to figure out what the limit is. In some examples, I can pick 15+ while in others it limits me to 8 options. 

The difference seems to be the length of the values. 

This example has 25 selected values before issue:
![image](https://user-images.githubusercontent.com/104051839/164152402-39865d29-89e2-4c21-8084-1c02f491365e.png)

but here it 11 and giving me the error:

![image](https://user-images.githubusercontent.com/104051839/164152707-925cade8-7fbc-4bf5-b67f-eaa1ff55c704.png)

My guess is it's some type of character limit, is there a way around this? 

Many Thanks!!

**Comment by Taaanos** [comment]
We are also running onto the same issue

**Comment by madkoo** [comment]
The field length limit is 255 chars.
