### ISSUE TITLE
Layout messed

### ISSUE THREAD

**Issue by danielstefanescu** [microsoft/vsts-extension-multivalue-control#202]
When I switch on the New Boards Hub feature in Azure DevOps Services the layout is messed up:
On:
![image](https://user-images.githubusercontent.com/19574258/168802029-c1988e6d-a37d-49cf-b756-e0782babb239.png)
Off:
![image](https://user-images.githubusercontent.com/19574258/168802145-94d22bd6-3fd9-4530-8a4a-40edc799ec53.png)

**Comment by us292231** [comment]
We are having this problem as well.  When the preview feature is turned on the choice list does not display and it is impossible to choose values.

**Comment by nuzolx** [comment]
Same issue for me

**Comment by madkoo** [comment]
This is fixed with the latest release. Closing the issue for now. Feel free to create a new issue if the issue persists.
