### ISSUE TITLE
Visual bug with selections due to whitespace

### ISSUE THREAD

**Issue by Joshua-Barclay** [microsoft/vsts-extension-multivalue-control#217]
When selecting options from the control the data is saved differently depending on the order of selection. In many cases the data will not have a leading space and won't match the UI component when reloaded.

Our control is defined with a backing multi-line text area and values separated by a semi-colon and a space:
Option A; Option B; Option C; Option D;
![image](https://user-images.githubusercontent.com/14132755/193191718-1f5c87e1-d148-4251-98c7-c84692339837.png)

When selecting options from the top-down (a, then b, then c) the values correctly tick in the UI:
![image](https://user-images.githubusercontent.com/14132755/193191858-f115338c-529a-48b1-b0c7-c82405ba14eb.png)
Notice the spacing in the 'data field' above - there's a space after each semi-colon.

When skipping the top option (select b, then c) the white-space no longer matches and the UI does not think the component is selected:
![image](https://user-images.githubusercontent.com/14132755/193192027-23b60028-d220-45a3-8f24-295867067df6.png)

This is a visual selection bug only (search and data export works as expected) but it does have a significant impact on user experience, especially in our scenario where there are dozens of selectable options.

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this.
