### ISSUE TITLE
Case sensitivity is not maintained when storing custom values

### ISSUE THREAD

**Issue by iGattreX** [microsoft/vsts-extension-multivalue-control#219]
When entering custom values in the control, the case sensitivity is not maintained, and all characters are converted to lower case by default.

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this.

**Comment by AminTi** [comment]
fixed

**Comment by iGattreX** [comment]
Thank you very much for fixing this bug. 👍👍

Regards
