### ISSUE TITLE
Loading indicator keeps spinning, control not showing

### ISSUE THREAD

**Issue by ndc** [Microsoft/vsts-extension-multivalue-control#22]
Screenshot of the error:

![multivalue error https](https://cloud.githubusercontent.com/assets/489308/26573750/16224a4c-4549-11e7-902f-ffee66d90936.png)

If I open the page with HTTP, the control is showing just fine. If I open the page with HTTPS, this error occurs.

This is on premise TFS 2017.

I saw in browser console there were two errors when loading `vsts-extensions-multivalue-control/1.0.5/assetbyname/dist/index.html`:

    SEC7111: HTTPS security is compromised by http://mytfsserver/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/vsts-extensions-multivalue-control/1.0.5/assetbyname/dist/index.html
    File: Backlog%20items
    SEC7111: HTTPS security is compromised by http://mytfsserver/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/vsts-extensions-multivalue-control/1.0.5/assetbyname/dist/index.html
    File: Backlog%20items

**Comment by mmanela** [comment]
This tells me that you probably have your TFS instance configured with a public url with the HTTP scheme. You can confirm this in the TFS Management Console.
![image](https://cloud.githubusercontent.com/assets/304410/26688697/4093da06-46a8-11e7-83c3-3c02b340af72.png)


You need to make sure that public url matches how you hit the site for the extensions to work correctly.
