### ISSUE TITLE
Hope support multiple checkboxes on pipeline releases to build variables

### ISSUE THREAD

**Issue by The-Mojoo** [microsoft/vsts-extension-multivalue-control#225]
I have used the **extended choice parameter** plug-in in Jenkins, which can be deployed in the support parameter.

When I used Azure DevOps Pipelines, I didn't find any similar functions, but found **vsts-extension-multivalue-control**. They look very similar, but their working locations are different. I looked at the source code and didn't understand it very well. So I don't know whether it would be difficult to support Pipelines.
![微信截图_20221209165238](https://user-images.githubusercontent.com/11498170/206662961-673a56b8-9492-427c-a681-598f4b1870ea.png)

**Comment by The-Mojoo** [comment]
I've achieved my needs through the **Azure DevOps Services REST API**, checking out the microservice module through other web pages, passing in the relevant parameter combinations, and publishing on demand, but if this functionality is as good as **extended choice parameter** support, I feel it's still needed.

**Comment by AminTi** [comment]
We will add it to the backlog.
