### ISSUE TITLE
Can't input custom values if it's a prefix of a picklist string preset

### ISSUE THREAD

**Issue by randomuser369** [microsoft/vsts-extension-multivalue-control#228]
... apart from the fact that development of this extension is non-existent...

Suppose we have a picklist field, with presets:
- A pear
- A banana
... and both the control and the field are configured to allow custom/own values.

The user can't populate the field with "A" or "A p". That's a problem in cases where the picklist presets share a common prefix "MSFT ", but the desired value is "MSFT".

**Comment by AminTi** [comment]
Hi!, Thanks for reporting, we'll dig into this, and it will be fixed in an upcoming release.

**Comment by AminTi** [comment]
Hi, the issue is fixed.
