### ISSUE TITLE
How do I install in TFS 2015?

### ISSUE THREAD

**Issue by raedwa01** [Microsoft/vsts-extension-multivalue-control#23]
Instructions in the readme mention changing the config for work items in TFS 2015, but I cannot figure out how to install it in 2015.

**Comment by nschonni** [comment]
From the first line of the readme
> Currently only available on TFS 2017 or later and Visual Studio Team Services.

TFS 15 != 2015. Its TFS 2017 (or 15.0 in VS assembly version)

**Comment by mmanela** [comment]
Correct, we only support TFS 2017 or greater
