### ISSUE TITLE
Multivalue control by Microsoft DevLabs is taking longer than expected to load. Learn More about this extension, including available support options.

### ISSUE THREAD

**Issue by Nagarjunareddycarrier** [microsoft/vsts-extension-multivalue-control#232]
Hi Team,

When we try to create a requirement from Boards -- Backlogs - teams - specific team - epic - specific epic- feature - new requirement --> we receive below error.
Multivalue control by Microsoft <img width="906" alt="new-requirement-feature-issue" src="https://user-images.githubusercontent.com/124865037/217739091-6363666b-a0ce-4819-9d7f-79daa44cc988.PNG"> is taking longer than expected to load.[Learn More](https://cardos.carrier.com/_gallery/items/ms-devlabs.vsts-extensions-multivalue-control) about this extension, including available support options.

attached screenshot has detailed info

**Comment by Nagarjunareddycarrier** [comment]
FYI...
below is the version details of the extension

Extension details
A work item form control which allows selection of multiple values.
Publisher
Microsoft DevLabs
Installed version
2.2.29 (Latest)
Last updated
Jan 26, 2023 at 9:56 AM GMT+5:

**Comment by Nagarjunareddycarrier** [comment]
Can some one please consider this as priority -- this is blocking our project deliverales

**Comment by AminTi** [comment]
Hi, Thanks for reporting. We'll dig into this.

**Comment by Nagarjunareddycarrier** [comment]
> Hi, Thanks for reporting. We'll dig into this.

Thanks @aminTi , let us know if you need any further details which could help you

**Comment by AminTi** [comment]
Hi guys, I released an update and tested it,  It works as expected, please uninstall the extension and install it again.
let me know if you still have the same issues.
