### ISSUE TITLE
A blank picklist item gets added when "Allow users to enter custom values" option is selected

### ISSUE THREAD

**Issue by iGattreX** [microsoft/vsts-extension-multivalue-control#238]
Hi

A blank picklist item gets added to the list of the control when "Allow users to enter custom values" option is selected in the custom control options page.

![image](https://user-images.githubusercontent.com/8414158/220012143-6da774cb-efe6-41b3-8fd1-c789a9b13366.png)

I see this issue got introduced recently in the last couple of days (with the last build probably). It did not exist before.

Regards

**Comment by AminTi** [comment]
Thanks for reporting it will be fixed in an upcoming release.
