### ISSUE TITLE
We were hoping to clone this repo and create a single select control for our Azure DevOps instance

### ISSUE THREAD

**Issue by garagerock101** [microsoft/vsts-extension-multivalue-control#247]
Hi there, we love this control but would like to use the code to create our own control for single select tiems.  Can any of the contributors recommend how we would do this?  What typescript files we would need to midify etc.

Thanks!

**Comment by MOlausson** [comment]
Hi @garagerock101. In general we encourage contributions to this repository so others can benefit from that as well. What we want to avoid is enhanced open-source versions being added publicly on the marketplace. 

That said, if you're plan is to develop an internal version you can follow the guides in https://learn.microsoft.com/en-us/azure/devops/extend/overview?view=azure-devops and create a private extension that to then share within your organization.
