### ISSUE TITLE
Multivalue control not able to restrict user to add only values present in list in excel

### ISSUE THREAD

**Issue by lujinlou** [microsoft/vsts-extension-multivalue-control#248]
Reproduce steps:

1. Set Multivalue control filed in Work item and **disable** the Option: **Allow users to enter custom values**.
2. We will not able to set the custom value in DevOps UI.
![image](https://user-images.githubusercontent.com/52313100/234439976-078fb6a5-f957-481d-a5c8-cf76a519f137.png)
3. When we modify the field value in excel and update the work item. The custom field value will be added to the Multivalue control filed.
![image](https://user-images.githubusercontent.com/52313100/234440284-819a3a18-26b0-474e-94ca-4a76afff70e4.png)
Result:
![image](https://user-images.githubusercontent.com/52313100/234440348-7a53f3ee-e16d-40d6-983b-1d7b3516cc0e.png)

We need to restrict user to add custom value in excel and then update the work item.

We can report errors when updating work items in excel or directly restrict users from entering custom values in Multivalue control filed

**Comment by lujinlou** [comment]
@AminTi Can you take a look this ticket?

**Comment by AminTi** [comment]
we will look into this and get back to you sooner

**Comment by MOlausson** [comment]
Hi, this is a feature in the Excel add-in so nothing we can fix in the multi-value extension. Please add a suggestion for this in https://developercommunity.visualstudio.com/AzureDevOps.
