### ISSUE TITLE
Selecting multiple values is limited to 4 fields

### ISSUE THREAD

**Issue by eporopat** [microsoft/vsts-extension-multivalue-control#259]
If you select more than 4 values it errors with "Set the field eMail Distribution list1 to use suggested values rather than allowed values. "
It wont let you save more than 4 values, can this be increased?

**Comment by AminTi** [comment]
Hi, Thanks for reporting.  I'll have a look at it and will get back to you next week.

**Comment by dmstoltz4HAU** [comment]
@AminTi, I'm working with eporopat who logged the ticket above on this issue.
Please can you provide feedback.

**Comment by AminTi** [comment]
Hi, I couldn't reproduce the issue. I can select more than 4 items. Please let me know when you're available, and I'll be happy to assist you with that.

**Comment by dmstoltz4HAU** [comment]
Hi @AminTi , I'm working with Eddy on this and the issue is not the number of items added but rather the total character length of the items added.

I think the restriction is 256 characters.

If you add items and there total string length is greater than 256 then you will get the error.
