### ISSUE TITLE
Error message when attempting to select all options from picklist in extension

### ISSUE THREAD

**Issue by jdoorneck** [Microsoft/vsts-extension-multivalue-control#26]
I am receiving the error message "The field 'x' contains the value '1;2;3' that is not in the list of supported values" when choose all the options from the picklist for the extension.  I first created a picklist (string), and then created the extension from the picklist.

**Comment by mmanela** [comment]
The field you use needs to have its allowed values be marked as "suggested". Are you using XML based customization or UI based?

**Comment by jdoorneck** [comment]
Thanks for responding!  I'm using UI-based.

**Comment by mmanela** [comment]
You need to make sure you check ``` Allow users to enter their own values``` in the field you are using:
![image](https://user-images.githubusercontent.com/304410/29220913-8da9122e-7e71-11e7-89bf-17f2002ab2aa.png)
