### ISSUE TITLE
Multivalue control on XML based process not reflecting changes on UI once we modify/remove the values.

### ISSUE THREAD

**Issue by RanjanBKI** [microsoft/vsts-extension-multivalue-control#261]
We have requirement where workitem having multivalue control need to update like addition/removal values using XML based process.
After import workitem, we are not able to see the changes on UI part. Please do let me know how to proceed with steps/solution.

**Comment by RanjanBKI** [comment]
Hi Team,
Any update? The reason i am following as because we already implemented the changes on inherited model which works fine but fail to do on XML based due to this issues.

**Comment by AminTi** [comment]
Hello, are you available for a web session tomorrow?

**Comment by AminTi** [comment]
Feel free to reach out if you require any assistance.
