### ISSUE TITLE
multivalue control not working

### ISSUE THREAD

**Issue by obedsukazi** [microsoft/vsts-extension-multivalue-control#262]
selecting multiple values throws error:**The field 'Country' contains the value 'Botswana;Ghana;Kenya' that is not in the list of supported values.**

**Comment by MOlausson** [comment]
@obedsukazi the field must be "allow users to enter their own values", see https://github.com/microsoft/vsts-extension-multivalue-control#azure-devops-services for guidance.

![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/7904771/a5da589c-c6c7-4d1d-ad0b-de653b3f7a79)
