### ISSUE TITLE
WHEN condition not working for MultiValue Control

### ISSUE THREAD

**Issue by vksasmal** [microsoft/vsts-extension-multivalue-control#263]
I have two controls. one regular dropdown and other one is Multivalue control.

One basis of first drop down box, it should show the values in Multivalue control which is not happening. Every time, it shows me list of all values. Please help.

<FIELD name="SBU" refname="Custom.SBU" type="String" reportable="dimension">
	<HELPTEXT>Select Strategic Business Unit</HELPTEXT>
        <WHEN field="SDLCLite.Segment" value="Insurance">
          <ALLOWEXISTINGVALUE />
          <SUGGESTEDVALUES expanditems="false">
            <LISTITEM value="BDA" />
            <LISTITEM value="Foundational - ALL" />
            <LISTITEM value="Foundational GCA" />
            <LISTITEM value="Foundational non-GCA" />
            <LISTITEM value="GRS in US" />
            <LISTITEM value="GRS on GCA" />
            <LISTITEM value="International" />
            <LISTITEM value="London" />
            <LISTITEM value="USI" />
            <LISTITEM value="USI and BDA" />
            <LISTITEM value="USI and GRS" />
            <LISTITEM value="USI on GCA" />
          </SUGGESTEDVALUES>
        </WHEN>
        <WHEN field="SDLCLite.Segment" value="Multiple">
          <ALLOWEXISTINGVALUE />
          <SUGGESTEDVALUES expanditems="false">
            <LISTITEM value="Multiple" />
          </SUGGESTEDVALUES>
        </WHEN>
        <WHEN field="SDLCLite.Segment" value="Reinsurance">
          <ALLOWEXISTINGVALUE />
          <SUGGESTEDVALUES expanditems="false">
            <LISTITEM value="BDA" />
            <LISTITEM value="International" />
            <LISTITEM value="Multiple" />
            <LISTITEM value="US" />
          </SUGGESTEDVALUES>
        </WHEN>
      </FIELD>

<ControlContribution Label="Select Strategic Business Unit:" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
          	  <Inputs>
                	<Input Id="FieldName" Value="Custom.SBU" />
            	  </Inputs>
      		</ControlContribution>

**Comment by AminTi** [comment]
Hello, are you available for a web session tomorrow?

**Comment by vksasmal** [comment]
Sure, let me know what time?

**Comment by AminTi** [comment]
I will be available at 11:00 Central European Time.

**Comment by vksasmal** [comment]
11 AM CST works fine for me. Let me know how do I call you or share screen?

**Comment by AminTi** [comment]
Teams if you can

**Comment by vksasmal** [comment]
I have sent you the meeting invite. Lets talk tomorrow.
