### ISSUE TITLE
Not working since update 2.2.36 on Azure DevOps

### ISSUE THREAD

**Issue by bgdnsc** [microsoft/vsts-extension-multivalue-control#265]
Hey!

An update was just made 60 minutes ago on this, that I think could have potentially impacted the way the extension works on Azure DevOps? 
Tried Disable/Enable the extension, but it did not do anything. Tried re-adding a field again, did not do anything. Tried even reinstalling the extension in the Organization -- but that didn't work.

Any ideas/advices?

Thank you!
![devops1](https://github.com/microsoft/vsts-extension-multivalue-control/assets/74327540/f8cdaf23-080b-4120-bbcb-9580ccbdb20c)
![devops2](https://github.com/microsoft/vsts-extension-multivalue-control/assets/74327540/0bcbade5-6065-49dd-80e6-f4373f39d9f1)

**Comment by S-OAltr** [comment]
Can confirm, we're also have problems since the update got installed for us an hour ago. It's no longer possible to select items. Tested on multiple browsers with multiple accounts and devices

**Comment by mammothwizard** [comment]
What works is hovering your mouse cursor over the option you want to select and hit ENTER on keyboard :)

**Comment by bgdnsc** [comment]
The workaround I found working is "writing" in the field to filter through the values, until your reach one, and then hitting enter.

**Comment by mammothwizard** [comment]
> The workaround I found working is "writing" in the field to filter through the values, until your reach one, and then hitting enter.

but you need to write the full option, partial search and ENTER does not work, right? At least that's how I experience it on my side.

**Comment by bgdnsc** [comment]
In my case it works with partial search -- important thing is to have only 1 value remaining & pre-filtered 

But I did this before:
- disable & enable extension
- uninstall & install extension

**Comment by AminTi** [comment]
I'm sorry for any trouble this might have caused.  Our team has found and fixed the problem. We've tested the solution carefully, and I'm happy to let you know that the new release will be available in just 30 minutes from now.

**Comment by mammothwizard** [comment]
> I'm sorry for any trouble this might have caused. Our team has found and fixed the problem. We've tested the solution carefully, and I'm happy to let you know that the new release will be available in just 30 minutes from now.

Excellent news. Do I need to reinstall the extension?

**Comment by AminTi** [comment]
We've just released a new update. Please let me know if you're still encountering the same issue.

**Comment by BKMercer** [comment]
This appears to be fixed. Thank you for your prompt attention to this matter.

Brian Mercer | ADO Tools Team | Huntington National Bank | Phone: 614.331.5073 |  Mobile: 614-395-2586 Time Zone: EDT / EST

Can-Do Attitude / Service Heart / Forward Thinking / Meals-on-Wheels Team

OOO Awareness: TBD

The Huntington National Bank / 7 Easton Oval / EA3W21  / Columbus, OH 43219 / huntington.com<https://www.huntington.com/>

[pic]  ***@***.***



Internal Use


Internal Use

**Comment by mammothwizard** [comment]
I can confirm it works on my end as well. Thanks a lot for a very swift response and resolution :) much appreciated!
