### ISSUE TITLE
Extension not working after last update

### ISSUE THREAD

**Issue by Tronko86** [microsoft/vsts-extension-multivalue-control#266]
Extension not working after last update:
- I can't select suggested value
- I can't enter new value

I can only remove selected value.

![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/45765476/a547b2aa-b728-4524-8b29-3e54766e7ed7)

![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/45765476/246a99cd-0528-4be3-8ba0-4b60d8ada8c8)

**Comment by MatthewDiPietroTR** [comment]
We are experiencing the same. Previously selected values are displayed, but new values cannot be selected.

**Comment by esfernandez** [comment]
In ours teams, we can't select value in multivalue-control.

**Comment by Tronko86** [comment]
problem resolved with new fix

![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/45765476/2438eff3-83eb-4c9a-aab8-2fb1ab5ef2aa)

**Comment by AminTi** [comment]
Yes, We've released a new update yesterday.
