### ISSUE TITLE
Taking a long time to load

### ISSUE THREAD

**Issue by TRSwami** [microsoft/vsts-extension-multivalue-control#274]
Getting the error:

Multivalue control by Microsoft DevLabs is taking longer than expected to load.[Learn More](https://marketplace.visualstudio.com/items/ms-devlabs.vsts-extensions-multivalue-control) about this extension, including available support options.

All of the sudden seeing this error,

Disabled the new boards theme and layout too.

**Comment by AminTi** [comment]
can you describe your environment?

**Comment by AminTi** [comment]
If you're still experiencing the same issue, please reach out to me on Teams at [amin.titi@solidify.dev](mailto:amin.titi@solidify.dev
