### ISSUE TITLE
Multivalue control by Microsoft DevLabs is taking longer than expected to load

### ISSUE THREAD

**Issue by UzairKhan2598** [microsoft/vsts-extension-multivalue-control#278]
Issue: Whenever we are trying to create any work item we are getting below error: "Multivalue control by Microsoft DevLabs is taking longer than expected to load. Learn More about this extension, including available support options." This issue occured two weeks ago and it has been happening frequently. 

Environment : Production and there has been no recent changes in the production environment 

Troubleshoot : We troubleshooted this issue twice. In the first troubleshoot after upgrading the extension to 2.2.37 it was working as expected, then after a few days we encountered same issue so we tried to uninstall and reinstall the extension but unfortunately, we are getting the same error again.
![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/143694036/3b70be78-6fc3-4aa2-b72b-5dee62144419)

**Comment by AminTi** [comment]
Hello, are you available for a web session?

**Comment by UzairKhan2598** [comment]
> Hello, are you available for a web session?

screen shot will do? ...as its difficult to connect outside network

**Comment by AminTi** [comment]
I could not reproduce the issues. Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors?

**Comment by AminTi** [comment]
If you continue to experience the same issue, please inform me.

**Comment by UzairKhan2598** [comment]
Hi Team , we are getting following error intermittently “Multivalue control by Microsoft DevLabs failed to load."
 
Due to corporate restriction we are unable to share log , but while troubleshooting we figured out following :-
 
1. When this extension works it connects with our Azure devops fqdn , but when we receive the above error ( in network tab ) we can see extension trying to connect with azure devops app IP instead of fqdn and throws this error in console " ERR_CERT_COMMON_NAME_INVALID ".

2. we observed that the extension tries to send request to [ https://IP address//_apis/public/gallery/publisher/ms-devlabs/extension/vsts-extensions-multivalue-control/2.2.38/assetbyname/dist/multivalue.html ] but we receive following error :- failed to load response data no resource with given identifier found.

3. On exporting log we found this error  - \”errorMessage\":\"Error: Cannot get registered instance for : ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control\\n    at https://URL/_public/_Bundling/Content?bundle=vss-bundle-async-vyuI25Wa2qSnUdfc8ONld2A3OMJmllyZvdbHfDHeck-2Gic=:279:1051\\n    at l (https://URL/_public/_Bundling/Content?bundle=vss-bundle-common-vJV5sA5LIedtnC9MfvqKqsPWFBEZKb_lxdEU9Agg28TFfc=:33:8126)

Please help us in fixing this issue at the earliest
