### ISSUE TITLE
Error displaying on multi select 

### ISSUE THREAD

**Issue by laurenmccarthy1** [microsoft/vsts-extension-multivalue-control#282]
hiya

i have started getting a couple of errors: 
![extenstion error 1](https://github.com/microsoft/vsts-extension-multivalue-control/assets/150936679/44c25ad3-f0c4-4066-88ba-d7a91f503dca)

which i havent seen before.  
I wasnt having this before (i havent done it for a while though) 

Thanks

**Comment by AminTi** [comment]
Hi, I just tested it, and it works as expected. I think you should check the configuration again. Please take a screenshot and share it with me.

If you have any further requests or questions, feel free to let me know!

**Comment by laurenmccarthy1** [comment]
Ahh changing the field to “Allow users to enter their own values” has resolved it
