### ISSUE TITLE
Multivalue control does not work In Test Plan

### ISSUE THREAD

**Issue by Thilas** [microsoft/vsts-extension-multivalue-control#286]
I just noticed that Multivalue control is not working when opening a work item from Test Plan, whereas it works perfectly from Azure Boards.

KO:
![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/3749820/9a03be81-db14-468e-9cad-c6d2eb298c33)

OK:
![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/3749820/06a511f1-8758-4e9a-acb9-2197c2f7209e)

Thank you.

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this.

**Comment by MOlausson** [comment]
@Thilas I've tried both old and new boards hub with version 2.2.39 and it works fine on a test case both when opened from a test plan and from a query. Let us know if you still have problems with your setup.

**Comment by AminTi** [comment]
I will close this issue. If you encounter the same problem again, please inform us.
