### ISSUE TITLE
Azure DevOps Marketplace Extension Update?

### ISSUE THREAD

**Issue by shaun-borlinghaus** [microsoft/vsts-extension-multivalue-control#289]
Issue 280 was marked as closed/completed in #283 on 17-November -- when will this make it to the Azure extension Marketplace for DevOps services? The latest version there (2.2.38) was last updated 19-October, so we still have the same issue there.

**Comment by mavsguy482** [comment]
We are also waiting for this fix to make it into a new version. I refresh our Installed extensions page daily within Azure DevOps, hoping that this fix will finally make it into a new version release.

**Comment by AminTi** [comment]
Hello, the issues have been resolved. We haven't deployed it to production yet, which is why you may not have seen the changes.

**Comment by shaun-borlinghaus** [comment]
that's good to hear. any ETA on when it'll release to production for Services?

**Comment by shaun-borlinghaus** [comment]
Are we able to get an ETA on the production deployment before this is closed? We have people asking about this almost daily at this point.
