### ISSUE TITLE
"The Element "WebLayout" has invalid child element "Extensions"

### ISSUE THREAD

**Issue by pguerre** [Microsoft/vsts-extension-multivalue-control#29]
I added this extension in TFS 2017.2 (on-premise). however, when attempting to upload a WIT xml with the extensions element, Bug WIT, for example, I get an error saying the "The Element "WebLayout" has invalid child element "Extensions". List of possible elements expected: "Page, PageContribution". Is this a bug?

**Comment by mmanela** [comment]
You need to make sure Extension is the first element under <WebLayout>. Did you put it after <SystemControls>?

**GOOD**
```
     <WebLayout>
        <Extensions>
           <Extension Id="mmanela.vsts-workitem-recentlyviewed" />
        </Extensions>
        <SystemControls>
          <Control Type="FieldControl" FieldName="System.Title" EmptyText="Enter title" />
        </SystemControls>
```

**BAD**
```
     <WebLayout>
        <SystemControls>
          <Control Type="FieldControl" FieldName="System.Title" EmptyText="Enter title" />
        </SystemControls>
        <Extensions>
           <Extension Id="mmanela.vsts-workitem-recentlyviewed" />
        </Extensions>
```

**Comment by pguerre** [comment]
great thank you! that worked, I found an article and it placed it after the system controls element.
https://blogs.msdn.microsoft.com/devops/2017/01/13/new-work-item-form-in-tfs-2017/

**Comment by mmanela** [comment]
@pguerre  Ill update the blog to call this out explicitly. And Ill see if we can improve that error message. Thanks!
