### ISSUE TITLE
Combination of Multivalues are not allowed, however to set particular combination is optional

### ISSUE THREAD

**Issue by TrivediPriyanka** [microsoft/vsts-extension-multivalue-control#294]
### Urgent: Multivalue field does not allow to add a combination of values apart from those mentioned in the Input list which is optional do

https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-extensions-multivalue-control

From the above reference, the control is allowing the field to have multiple values from the picklist, but in such cases, if we have multiple values like 200-300 in the picklist, it's not feasible that you add 'n' number of combinations in the field configuration like below:

![image](https://github.com/microsoft/vsts-extension-multivalue-control/assets/90563393/c5a051a7-6d70-42dc-862d-225f4b2fe3e6)

Since I have a large number of picklist values, not able to enter n number of combinations
and as mentioned there only, it is optional to do, but not able to have multiple different combinations 

@ostreifel
@AminTi
@mmanela
@joserady
@dependabot[bot]
@madkoo
@mohitbagra
@obvioussean
@Joshua-Barclay
@nschonni
@cschleiden
@liang2zhu1
@ubergeekgirl
@gamontal

**Comment by MOlausson** [comment]
@TrivediPriyanka this is a complex case that this extension is not built to handle. Feel free to use the code to implement a custom extension for your needs.
