### ISSUE TITLE
Unable to select multiple values, Select all is not working after certain limit

### ISSUE THREAD

**Issue by Akshay-0799** [microsoft/vsts-extension-multivalue-control#296]
Hello Team,
I am trying to pick all values from the field, there are 40 values total but it is only allowing me to pick 30 values only, If I select 40 values it is giving me an error
![Capture](https://github.com/microsoft/vsts-extension-multivalue-control/assets/155723804/865c8052-70e9-4e49-afcd-d237b5bb8ab0)

**Comment by AminTi** [comment]
I will look into the issue and update you once I have more information.

**Comment by AminTi** [comment]
![Screenshot 2024-04-18 at 15 13 34](https://github.com/microsoft/vsts-extension-multivalue-control/assets/54841342/ff11e33b-53aa-4657-9d95-a76501715fe6)
I've just tested it, and it's functioning as expected on my end. Could you please provide us with the network and console logs for further analysis
