### ISSUE TITLE
How can I set Multivalue Control fields using Logic App?

### ISSUE THREAD

**Issue by kyle-vp** [microsoft/vsts-extension-multivalue-control#298]
I have a logic app that creates an email pre-flight Task, and I want to pre-populate the Multivalue Control with the required checklist items. I don't see that I can do that.

**Comment by AminTi** [comment]
Hi, it's not possible to automatically prepopulate the multi-value field, but for example if you set 'Acceptance Criteria' as the field; anything you input there, like 'Windows; Mac; PC,' will populate the multi-value.
