### ISSUE TITLE
Multi work items select can not edit(add) because edit would remove all previous values and only add the new value

### ISSUE THREAD

**Issue by Amna56** [microsoft/vsts-extension-multivalue-control#299]
Want to enable users to do multi work items update on a field with multi select capablity. at the moment any multi work item select and  right click and choose edit >> then you try to update the multi select field. it would reset any pervious values to only the updated value

**Comment by AminTi** [comment]
Hi, @Amna56  Could you please provide an example with a few images

**Comment by Amna56** [comment]
![multiselect-edit](https://github.com/microsoft/vsts-extension-multivalue-control/assets/12409682/970776ba-e708-4822-b497-f7d6b967a45f)
![multiselect-multivalue](https://github.com/microsoft/vsts-extension-multivalue-control/assets/12409682/1ec9e092-a5d3-4c09-9942-3803e76d5026)
![multiselect-tags](https://github.com/microsoft/vsts-extension-multivalue-control/assets/12409682/69a7f562-e647-402d-af6a-ae8d6eb66a3b)

**Comment by Amna56** [comment]
as you can see that the tags can be multi line has an add option on edit but for the multivalue edit (for Governed by field) it is only update so they would overwrite any previous values.

**Comment by AminTi** [comment]
Hello again, I'm having trouble understanding what you want to achieve, and it seems we don't have an edit option for multi-value control. Please double-check that we are discussing the correct extension!

**Comment by Amna56** [comment]
Hello, the edit option is avaliable for all workitems avaliable in the boards. 
you can select multiple workitems and choose to edit them all together.
if i try to do this for  a multivalue field it would overwrite any values that were already there. but it possible to have an an option to add values instead over writing the overwriting.

**Comment by AminTi** [comment]
This behavior in Azure DevOps is by design and, unfortunately, cannot be prevented in the multivalue extension. As a third-party extension, we do not have control over the built-in edit tool's functionality.
