### ISSUE TITLE
Limit Displayed Values in REST Multi-Value Extension Control

### ISSUE THREAD

**Issue by prabhat9999** [microsoft/vsts-extension-multivalue-control#308]
Hello,

I'm using the REST Multi-Value Extension Control, and I'm currently facing an issue with how the values are being displayed. Right now, all 7,000+ values are shown in the dropdown, which is overwhelming for users.

What I'm trying to achieve:

I want to limit the displayed values to only the most relevant.
Users should still have the ability to filter out and select any of the other values by typing in the search box.

**Comment by AminTi** [comment]
Hi, Unfortunately, at this moment, there isn't an option to limit the displayed values while still allowing users to search and filter the others.
However, we appreciate your input and will keep this in mind for future improvements. Please don't hesitate to reach out if you have any other questions or concerns.
