### ISSUE TITLE
error “The field ‘x’ contains the value ‘Y;Z’ that is not in the list of supported values.”

### ISSUE THREAD

**Issue by jbenton8** [microsoft/vsts-extension-multivalue-control#313]
I can no longer select more than 1 value for the multivalue control extension. It was working fine the other day and now it's not. 

I tried the suggest solution of uninstalling then reinstalling and it is still throwing the error “The field ‘x’ contains the value ‘Y;Z’ that is not in the list of supported values.”

I tried following the thread of other people reporting the issue and cannot see any other solution to resolve this.
https://developercommunity.visualstudio.com/t/Multivalue-Control-no-longer-allow-multi/1247278

Looks like Ging Yuan[MSFT] is the person to talk to, but I don’t know how to get a hold of them. Please help! Our team really needs this extension back up and running.

Here is the documentation it sends me to which is also not helpful: https://github.com/Microsoft/vsts-extension-multivalue-control#azure-devops-services
![1](https://github.com/user-attachments/assets/377e1e16-0a6a-43a7-8a81-5286ce5021be)
![2](https://github.com/user-attachments/assets/7fcfb3a9-cc61-4949-8d19-717b1d81f571)

**Comment by danhellem** [comment]
@jbenton8 can you try and turn off New Boards Hub preview and see if that changes things?

**Comment by AminTi** [comment]
Hi, if you still need help, please let me know.
