### ISSUE TITLE
vsts-extensions-multivalue-control by ms-devlabs failed to load

### ISSUE THREAD

**Issue by alexvaccaro** [Microsoft/vsts-extension-multivalue-control#32]
Hi,

On occasions the form fails to load the extension with the message "vsts-extensions-multivalue-control by ms-devlabs failed to load."
This seems to be happening randomly, what are the possible causes of this? Is there a log I can review to identify the underlying cause?

**Comment by ostreifel** [comment]
Are there any JavaScript exceptions or http request failures in the in the browser console (f12)?

**Comment by mmanela** [comment]
@alexvaccaro Are you on TFS or VSTS?

**Comment by alexvaccaro** [comment]
TFS 2017.2

**Comment by localbuzz1** [comment]
Just started having this issue today in TFS2017.   Any thoughts on how to fix this issue?

**Comment by formeroosid** [comment]
I'm getting this error in the browser:
![image](https://user-images.githubusercontent.com/5659343/35416274-67e03424-01dd-11e8-8edd-2b52c3c7662a.png)

**Comment by formeroosid** [comment]
Just started this morning for us as well. This has been working for the last 6 months. :-/

**Comment by mmanela** [comment]
@mohitbagra  and @ostreifel  Can you two take a look? Is this a deployment issue?

**Comment by mohitbagra** [comment]
@formeroosid  Do you see any request being failed in the network tab?

**Comment by mmanela** [comment]
@formeroosid  Is this on VSTS  (cloud) on TFS (box)?

**Comment by formeroosid** [comment]
It’s an on-premise install

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by formeroosid** [comment]
I’ll check.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by formeroosid** [comment]
No errors in the Network tab.

**Comment by mmanela** [comment]
Is it happening consistently?

**Comment by formeroosid** [comment]
Nope. It stopped happening as of this morning. Any logging I can look at
for clues?

Jamie

**Comment by mohitbagra** [comment]
This issue mostly happens if the extension fails to load any resource (like the html file or a javascript file). Next time you see this error, please check in the debugger console here -
![image](https://user-images.githubusercontent.com/3766956/35456299-fce7c922-02a2-11e8-9817-57f1388df25a.png)

This tree shows all the files requested and loaded by the multi value control extension. I am assuming that one of these files didnt get loaded and thats why you saw that error. So next time when you see this error, just open dev tools and check this tree for multi value control

**Comment by mohitbagra** [comment]
This area specifically - 
![image](https://user-images.githubusercontent.com/3766956/35456351-1eb5f16e-02a3-11e8-872e-9b8978b9b23e.png)

**Comment by mmanela** [comment]
@formeroosid Are you still having this issue? @alexvaccaro

**Comment by alexvaccaro** [comment]
I saw the issue again a couple of days ago, the next time it happens I will check those files.

**Comment by formeroosid** [comment]
No. We have not seen a recurrence of the issue.

Jaime

**Comment by mmanela** [comment]
Closing for now until we get data from a re-occurance

**Comment by johnsjg** [comment]
Hi I am having the same issue should I open another ticket?

**Comment by yayitserica** [comment]
I’m also experiencing the same issue in my VSTS instance.

**Comment by mmanela** [comment]
@yayitserica  @johnsjg Are you both on VSTS? What are you account names? How often is this happening for you and with what extensions?
