### ISSUE TITLE
Control does not hide when READONLY and EMPTY 

### ISSUE THREAD

**Issue by AndGoe** [Microsoft/vsts-extension-multivalue-control#33]
The control does not hide if it´s empty and set to READONLY (or set to EMTPY and READONLY explicitly) like other controls.
We are using this to show or hide specific fields of the work item, but for the multivalue control this does not work. It is shown and values can be selected but then the error "The value for field 'field name' must be empty." is printed on top of the work item.

Is this an explicit decision or just not implemented yet?

**Comment by mmanela** [comment]
For not this is a specific decision. The custom controls are general and the form does not know if you are using it just for display information or data input (we have seen both). For this reason the form doesn't try to hide the controls. We could in the future add more metadata to understand the intent of the extension but this is not in the current plans.

**Comment by AndGoe** [comment]
Thanks for your answer!
But in fact the custom control tries to be general, shouldn´t it behave as the other controls? This means it should be hidden, if declared EMTPY like the built-in controls are doing in my opinion ...
At least a property to set or any other mechanism to enable this behaviour would be very helpful!
