### ISSUE TITLE
Multivalue fields not visible in test manager or visual studio 2015

### ISSUE THREAD

**Issue by Stviane** [Microsoft/vsts-extension-multivalue-control#34]
We have added multi-values fields on a work item this is visible in tfs 2017 update 1 (webview)  but not visible to the user that is accessing the platform via test manager and/or visual studio.

**Comment by jawn** [comment]
I see the same issue.

**Comment by jawn** [comment]
Just found #6. If this is still true it would be helpful to mention the lack of support for Visual Studio in the readme/homepage.

**Comment by ostreifel** [comment]
Thanks for the feedback. This work is now scheduled for this and similar extensions.

**Comment by ostreifel** [comment]
As in #6 extensions can only be used in the web version of the product.
