### ISSUE TITLE
[Question] Is it possible to integrate a scroll bar and a live search like tags?

### ISSUE THREAD

**Issue by TFSRobert** [Microsoft/vsts-extension-multivalue-control#35]
**Hello,**

it is possible to integrate a scrollbar when there are to many values.
I have one hundred entries and the field where i choose the entries is very very long.
I do not mean the result field when the field is collapsed.

And it is possible to integrate a live search box. That means that i can search for entries like tags.

Best regards and **many thanks for this nice extension**
Robert

**Comment by mmanela** [comment]
@TFSRobert  That is a great suggestions. @mohitbagra  and @ostreifel  for their thoughts?

**Comment by HakX91** [comment]
Please implement these features. This would be a very helpful upgrade especially wen the Allowed Values list is very long and even more helpful when using a laptop (no traditional mouse-scroll).

**Comment by ostreifel** [comment]
Added a search box. The changes are now live. Please file additional issues if you encounter any problems.
