### ISSUE TITLE
Not able to select multiple values

### ISSUE THREAD

**Issue by ravneetarora** [Microsoft/vsts-extension-multivalue-control#37]
multivalue control is not working at my end. I am performing the below steps:
1) In the process template; adding a new field "ListOS" with a type "Picklist (string)".
2) In the options selecting the "Required" checkbox"
3) Adding the values "1", "2","3","4"
4) Adding a multivalue custom control
5) In the options selecting Picklist field created in step1

Using the multivalue control in workitem in VSTS
6) Creating a new workItem type "Bug"
7) Selecting multiple values from "ListOS"
8) It throws the message "The field 'ListOS' contains the value '1;2;3;4' that is not in the list of supported values."

Please help where am i going wrong?

**Comment by mmanela** [comment]
You need to make sure you check __Allow users to enter their own values__

![image](https://user-images.githubusercontent.com/304410/33839916-50c13616-de48-11e7-941b-8a9ad705f5dd.png)

**Comment by ravneetarora** [comment]
Thank you. It worked!
