### ISSUE TITLE
The field "Operating Systems" contains the value "Windows; Linux" that is not in the list of supported values

### ISSUE THREAD

**Issue by Jose-CF** [Microsoft/vsts-extension-multivalue-control#38]
I followed the instructions as described in the page of the control.

If I try to set one OS  it works fine. If select more than one, I get the error as presented in the title.

Please fix.

**Comment by ostreifel** [comment]
It sounds like the backing field has been given a set of allowed values - switch these to suggested if you want to be able to select 2 or more values at once. Otherwise switch the backing field from a picklist field to a text field

**Comment by Jose-CF** [comment]
Ok, it worked. I understood wrongly how to configure the control from the instructions in vsts marketplace... or are the instructions confusing?

So ok it is working.
