### ISSUE TITLE
Search the multivalue control

### ISSUE THREAD

**Issue by RafaelMontegordoFelix** [Microsoft/vsts-extension-multivalue-control#40]
Hi there,
This control have autocomplete?
It's possible to search a value in the list of values?

The problem is, i'm trying to use this component to add people, and i would like to filter does values.

Thanks

**Comment by mmanela** [comment]
@mohitbagra  and @ostreifel  Thoughts?

**Comment by mohitbagra** [comment]
We can use something like Fabric's tag picker. It supports multiple values and search functionality. 
https://developer.microsoft.com/en-us/fabric#/components/pickers

**Comment by mohitbagra** [comment]
The only downside is that this control doesnt have a "open dropdown" icon to see all available values. Users will see a dropdown with filtered resutls when they type something.

**Comment by ostreifel** [comment]
I think we should do as the contributions graph does for repos
![image](https://user-images.githubusercontent.com/5203542/43482468-9db41106-94bd-11e8-80fd-0d8e9323db93.png)
This would alleviate #56 as well

**Comment by ostreifel** [comment]
Would also fix #35

**Comment by ostreifel** [comment]
These changes are now live. Please file additional issues if you encounter any problems.
