### ISSUE TITLE
Required icon is not show against field

### ISSUE THREAD

**Issue by Scott-Emberson** [Microsoft/vsts-extension-multivalue-control#41]
When using this field it does now show the required icon. 
Example of the icon against a standard work item field.

![image](https://user-images.githubusercontent.com/8268155/36353072-a2e66946-14b9-11e8-9930-e0b4cefd642b.png)

The multivalue list does not show it even though it's required. 

![image](https://user-images.githubusercontent.com/8268155/36353080-c022b802-14b9-11e8-9236-3c0b3ee69d08.png)

It does still show at the top of the work item when creating it but it should also show against the field.

![image](https://user-images.githubusercontent.com/8268155/36353093-e6dab13e-14b9-11e8-9bfa-29c1a91ea4fc.png)

Server: Windows Server 2016
TFS Type: On-premises
TFS Version: 2017.3

**Comment by mmanela** [comment]
@ostreifel I think you fixed this on VSTS. Can you confirm whata TFS version will contain it?

**Comment by ostreifel** [comment]
This will be released onprem in the upcoming TFS 2018 update 2. Solution is to either wait for that to be released or use VSTS
