### ISSUE TITLE
Limit of 255 char?

### ISSUE THREAD

**Issue by LarsLedin** [Microsoft/vsts-extension-multivalue-control#43]
Hi, 
I need a pretty long list in our multivalue but it seems to be a limit of 255 char. 

Is it possible to change this?

**Comment by nschonni** [comment]
No, 255 is the length for the TFS string type https://docs.microsoft.com/en-us/vsts/work/customize/reference/define-modify-work-item-fields

**Comment by ostreifel** [comment]
use an html or plaintext field
Example
![image](https://user-images.githubusercontent.com/5203542/36819086-b8f9aaf0-1c9c-11e8-9cbf-2e08e95e214a.png)
