### ISSUE TITLE
Trying to use SuggestedValues from GlobalList gives error TF201067 when loading WIT to TFS2017.3

### ISSUE THREAD

**Issue by MarkusLaakso** [Microsoft/vsts-extension-multivalue-control#44]
Trying to use SuggestedValues from GlobalList gives error TF201067 when loading WIT to **TFS2017.3**

If I have the ListItem values for SuggestedValues under the Field definition in the WIT, it works.

However, when I move the same ListItem values under a GlobalList definition and try to use that GlobalList from the same Field definition, then WIT import fails and gives unrelated error message: "TF201067: You do not have permission to modify the work item type or field. You must have permission to modify work item types and fields in each team project where they are used. If you have the necessary permissions, your work item metadata cache may be out of date. Refresh any cached metadata and try the operation again."

Definitely, the error message is unrelated, because if I immediately move the ListItem values back to the SuggestedValues under the Field definition in the WIT, it works without issues.

It is important to be able to define the SuggestedValues as a GlobalList.

Microsoft Visual Studio Team Foundation Server
Version 15.117.27024.0

      <FIELD name="XYZ" refname="VMS.ADLM.XYZ" type="PlainText">
        <SUGGESTEDVALUES expanditems="true">
          <LISTITEM value="XA" />
          <LISTITEM value="XB" />
          <LISTITEM value="XC" />
          <LISTITEM value="XD" />
        </SUGGESTEDVALUES>
      </FIELD>

C:\Projects\1-VMS\Non-Production\ADLM\Dev\WorkItemTypes>ImportWIT2tfs-2017sb.bat ADLMDEV Requirement.xml'
Fri 03/02/2018  9:06:23.22
The work item type import has completed.
Fri 03/02/2018  9:06:31.12

      <FIELD name="XYZ" refname="VMS.ADLM.XYZ" type="PlainText">
        <SUGGESTEDVALUES expanditems="true">
          <GLOBALLIST name="VMS.ADLM.XYZvalues" />
        </SUGGESTEDVALUES>
      </FIELD>

C:\Projects\1-VMS\Non-Production\ADLM\Dev\WorkItemTypes>ImportWIT2tfs-2017sb.bat ADLMDEV Requirement.xml
Fri 03/02/2018  9:08:20.05
_TF201067: You do not have permission to modify the work item type or field. You must have permission to modify work item types and fields in each team project where they are used. If you have the necessary permissions, your work item metadata cache may be out of date. Refresh any cached metadata and try the operation again._
Fri 03/02/2018  9:08:23.07

**Comment by ostreifel** [comment]
This may be better served by using the [Rest Multi Value Extension](https://marketplace.visualstudio.com/items?itemName=ottostreifel.vsts-rest-multivalue-control) in combination with [these](https://docs.microsoft.com/en-us/rest/api/vsts/processdefinitions/lists/get?view=vsts-rest-4.1) rest apis
