### ISSUE TITLE
Getting error "not in the supported list of values"

### ISSUE THREAD

**Issue by rlheman** [Microsoft/vsts-extension-multivalue-control#5]
After setting up the Multivalue control I tested it and when I choose more than one I get an error saying "The field 'Products' contains the value ' (9 names of my products) that is not in the list of supported values."  The custom field is originally set up as a string picklist. I get that error when I try using just the picklist.  I tried setting up it up using the individual fields like in the example but get the same error. I tried just the semicolon no spaces and semicolon with a space in between each name.  I get the error both ways. I tried in both Chrom and IE 11 but got the same error.  I then tried it in a different VSTS instance and it worked there.  The first is my production environment that was set up in June this year. The 2nd instance is a personal instance set up several years ago.  I've attached a screenshot with the error.
![multivalue](https://cloud.githubusercontent.com/assets/19841542/20537171/4a8cfec4-b0a9-11e6-900d-8ed4da924e66.PNG)

**Comment by mmanela** [comment]
You need to set the picklist to let user's add their own values:
![image](https://cloud.githubusercontent.com/assets/304410/20537894/c85cf242-b0a3-11e6-8554-4feb3fa2b514.png)

**Comment by Palasin** [comment]
trying to add this control to one of our work items. please suggest what is wrong in following

<Group Label="Component:">
 <ControlContribution Label="Label" Id="ms-vsts-witiq.vsts-extensions-multi-values-control.multi-values-form-control">
                <Inputs>
                    <Input Id="ABC.VSTS.Components" Value="Component Names" />
                </Inputs>
            </ControlContribution>
              <Control Label="Component:" Type="MultiValueControl" FieldName="ABC.VSTS.Components">
                <CustomControlOptions />
              </Control>
            </Group>


can u upload a sample work item definition file

**Comment by rlheman** [comment]
Thank you. That seemed to work.

**Comment by Palasin** [comment]
can u upload a sample workitemdefiniton file which uses this control

**Comment by rlheman** [comment]
We are using Visual Studio Team Services so I do not have a workitemdefinition that I can post.

**Comment by sGambolati** [comment]
How is translated the check: "Allow users to enter their own values" into the XML? I have tried the [ALLOWEXISTINGVALUE](https://www.visualstudio.com/en-us/docs/work/reference/define-pick-lists#a-nameallowa-allow-an-existing-value) and had the same error.

**Comment by rlheman** [comment]
Sebastian have you tried SuggestedValues?  That lets you create an initial list but a user can add something else if they want (at least that's how I remember it working when I was using TFS).

**Comment by sGambolati** [comment]
Thanks! Solved using the SuggestedValues!
