### ISSUE TITLE
Using the Extension "Multivalue Control" doesn't allow for multi select to submit the ticket

### ISSUE THREAD

**Issue by jakevanderhoef** [Microsoft/vsts-extension-multivalue-control#51]
I am using the extension "Multivalue Control" so that when submitting a bug the reporter can select multiple browser versions, OS's, and devices. However if they do select more than one it returns the following error: "The field 'Device' contains the value 'Desktop;Mobile' that is not in the list of supported values." And does not allow the bug to be submitted. Please Advise. Thanks!

**Comment by ostreifel** [comment]
The field is currently configured to use allowed values, change it to suggested values.
