### ISSUE TITLE
Can't Set the chosen multivalue control values to read only

### ISSUE THREAD

**Issue by yayitserica** [Microsoft/vsts-extension-multivalue-control#53]
From my Motion/Submotion multi-control extension field, when I try to create a field rule to mark this as "read only" once a value is defined, I am not able to select any of the values:

![image](https://user-images.githubusercontent.com/15487798/42056212-6df2c74a-7ace-11e8-8297-c8c3c19b7153.png)

**Comment by ostreifel** [comment]
Can send me the xml configuration for the work item in question  (@ ottost@microsoft.com) and the steps for creating the issue described?

**Comment by ostreifel** [comment]
Please reopen if you find more information.
