### ISSUE TITLE
Control not honouring FIELD WHEN switch

### ISSUE THREAD

**Issue by sergemattu** [Microsoft/vsts-extension-multivalue-control#54]
I am using the control in this format: Input Id="FieldName" Value="CEN.Program" 
The field in question switches on the WHEN clause to show 2 different lists depending on another field on the form.
This control simply mashes both lists together as one set of suggested values rather than switching the lists. Am I doing something wrong?
When I use the default single select control in TFS, the lists are shown correctly.

**Comment by ostreifel** [comment]
The apis that are available to extensions do not support when rules when retrieving allowed values.
