### ISSUE TITLE
Upgrade from TFS 2015 to TFS 2018. Scroll Bar disappears when the Multi Value Control at the Bottom of the Layout

### ISSUE THREAD

**Issue by kriskoneru** [Microsoft/vsts-extension-multivalue-control#56]
I am placing Multi value control at the bottom of the page.  when the list is long i cannot scroll to the  both using the bar and when i try to use the scroll bar on the work item form it self the drop down list disappears which is very annoying and we are upgrading to on Prem TFS 2018.  **I tested this on Chrome, IE and firefox the issue exists.**

But on Microsoft Edge it works fine. 

Is there a resolution for this. 

![image](https://user-images.githubusercontent.com/16949860/43079174-65b229a0-8e5a-11e8-97ed-46065404f7b8.png)

**Comment by kriskoneru** [comment]
any update on this issue... ?????

**Comment by kriskoneru** [comment]
Correct. The issue happens when you using scroll bar. This did not happen when using previous deprecated extension. If you run on Edge it works fine using scroll bar also. I do not know if this an issue with the control it self.  

Business users still use scroll bars and the control should work irrespective of scroll bar or scroll bar on the mouse. 

As we are in the process of upgrade if it can be fixed that would be lot helpful.

**Comment by kriskoneru** [comment]
Is this issue fixed.... ??? Do i need to install new version of the control again.

**Comment by kriskoneru** [comment]
Is this issue fixed.... ??? Do i need to install new version of the control again.

**Comment by mmanela** [comment]
According to @ostreifel  this is a browser bug and there is not much we can do to work around.

**Comment by ostreifel** [comment]
Closing as this is a browser behavior outside the control of the extension.
