### ISSUE TITLE
Can't get proper syntax

### ISSUE THREAD

**Issue by aciccu** [Microsoft/vsts-extension-multivalue-control#57]
I'm trying to implement this on a TFS 2018 Hosted XML project and I'm unable to reimport the WIT. The extension is installed in my project. When I export the WIT (custom WIT) from TFS 2018, I see the Extensions section with the multivalue control info in it and I'm able to add the Extension tag. But I'm having problems with the correct syntax for implementing it in the Control. 

When I follow the instructions to insert the ControlContribution tag for the controls I want to have multivalues, I get errors on importing the WIT. Initially it was '<term> is unexpected token. Expecting white space.' It gives me a specific row and location, but there didn't seem to be any errors. 

When I tried other methods of inserting the ControlContribution tag I would get an error that ControlContribution isn't valid for the Column section. I tried to make ControlContribution a child of the Control field, but that also threw an error.

Also there is no Type="" in the ControlContribution tag, is Type now unnecessary?

Thanks,

**Comment by ostreifel** [comment]
You need to place the ```<ControlContribution>``` within a ```<Group>```
like this
![image](https://user-images.githubusercontent.com/5203542/43927788-80c8e86e-9be3-11e8-9b99-d6e4b8d467c4.png)
Detailed xml instructions can be found [here](https://github.com/Microsoft/vsts-extension-multivalue-control/blob/master/xmldetails.md)

**Comment by aciccu** [comment]
So I put it in the same group as the Control is in? And I leave the Control line and tags all the same? Is the Type Field Control or Multivalue Control?

Except I got this error upon import. 
![image](https://user-images.githubusercontent.com/42253392/43928723-c67a97d8-9be6-11e8-944f-0378abb3813f.png)

**Comment by ostreifel** [comment]
Make sure to use ```<WebLayout>``` not the old ```<Layout>```

The path to the Group that you are placing the ControlContribution is
/WITD/WORKITEMTYPE/FORM/WebLayout/Page/Section/Group


```xml
<ControlContribution Label="Label" Id="ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control">
    <Inputs>
        <Input Id="FieldName" Value="RefNameOfTheField" />
        <Input Id="Values" Value="ValueOne;ValueTwo;ValueThree;ValueFour" />
    </Inputs>
</ControlContribution>
```
