### ISSUE TITLE
Does it work with Visual Studio as well?

### ISSUE THREAD

**Issue by sdgmits** [Microsoft/vsts-extension-multivalue-control#6]
Does this Multi-Value control work with work items opened on Visual Studio form as well? 
**Ex**. If I have a multi value control on User story form, which should render properly on web client, but how it will render on local machine Visual Studio.  

Does it need any specific add-on to be installed on local machine to render it.  Note: We are using TFS 2015 Update 3 on-premise setup.

**Comment by mmanela** [comment]
The new extension model is __only__ for the web. So the extension would not show up inside of Visual Studio.
