### ISSUE TITLE
Can't install on TFS 2018 environment

### ISSUE THREAD

**Issue by kotani0006** [Microsoft/vsts-extension-multivalue-control#63]
Hello!
I found this amazing extension but I've got a problem.
It seems it can't be applied to TFS 2018 update2 on-premise environment.

At first, I tried to install it through Marketplace. I clicked install button and it says Something's gone wrong.
![image](https://user-images.githubusercontent.com/5116903/44880282-0076ab00-ace7-11e8-907e-bcddd662b4d2.png)

Then, I downloaded ths vsix version and run it on the server and I got the message saying, this extension cannot be installed to this product.
![image](https://user-images.githubusercontent.com/5116903/44880421-5a777080-ace7-11e8-88b1-108fddc7cbfb.png)

The text below is the log when the install faild.
It is saying that it detects Visual Studio Professional 2017 is installed before the installation failed, so I uninstalled Visual Studio Professional 2017 from the server but it doesn't work.

Is there any way to achieve the installation on TFS 2018?

※Sorry but some lines are written in Japanese.

> 2018/08/31 6:19:39 - Initializing Install...
2018/08/31 6:19:39 - 拡張機能の詳細...
2018/08/31 6:19:39 - 	Identifier         : vsts-extensions-multivalue-control
2018/08/31 6:19:39 - 	Name               : Multivalue control
2018/08/31 6:19:39 - 	Author             : ms-devlabs
2018/08/31 6:19:39 - 	Version            : 1.0.19
2018/08/31 6:19:39 - 	Description        : A work item form control which allows selection of multiple values.
2018/08/31 6:19:39 - 	Locale             : en-US
2018/08/31 6:19:39 - 	MoreInfoURL        : 
2018/08/31 6:19:39 - 	InstalledByMSI     : False
2018/08/31 6:19:39 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2018/08/31 6:19:39 - 
2018/08/31 6:19:39 - 	SignatureState     : Unsigned
2018/08/31 6:19:39 - 	サポートされる製品          : 
2018/08/31 6:19:39 - 		Microsoft.VisualStudio.Services
2018/08/31 6:19:39 - 			Version : 
2018/08/31 6:19:39 - 
2018/08/31 6:19:39 - 	参照                 : 
2018/08/31 6:19:39 - 署名の詳細...
2018/08/31 6:19:39 - 	Extension is not signed.
2018/08/31 6:19:39 - 
2018/08/31 6:19:39 - 適用可能な製品を検索しています...
2018/08/31 6:19:39 - 検出されたインストール済み製品 - グローバルな場所
2018/08/31 6:19:39 - 検出されたインストール済み製品 - ssms
2018/08/31 6:19:39 - 検出されたインストール済み製品 - Visual Studio Professional 2017
2018/08/31 6:19:39 - VSIXInstaller.NoApplicableSKUsException: この拡張機能は、現在インストール済みの製品にはインストールできません。
   場所 VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   場所 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   場所 VSIXInstaller.App.Initialize()
   場所 System.Threading.Tasks.Task`1.InnerInvoke()
   場所 System.Threading.Tasks.Task.Execute()

**Comment by ostreifel** [comment]
Installation needs to be done through the browser of tfs

Some guides on installation on tfs
https://blogs.msdn.microsoft.com/devops/2016/03/31/team-foundation-server-extensions-2/
https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=tfs-2018

After that is done you will need to update the work item form to use the new extension.

Export the process template
https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/witadmin-import-export-process-configuration?view=tfs-2018
Locate the weblayout for the work item type you want to customize
https://docs.microsoft.com/en-us/azure/devops/reference/xml/weblayout-xml-elements?view=vsts
Then add the xml for the multivalue control 
https://github.com/Microsoft/vsts-extension-multivalue-control/blob/master/xmldetails.md
Import the the process xml back to the server.
