### ISSUE TITLE
MultiValued control pop up is not shown in Internet Explorer

### ISSUE THREAD

**Issue by OmprakashLimbhore** [Microsoft/vsts-extension-multivalue-control#67]
Hi,
We have used multivalued control. It works fine in Google Chrome(Version 68.0.3440.106 (Official Build) (64-bit))

Bit is is not showing the pop up in Internet Explorer(V11.611.16299.0)
Can you investigate and let us know the solution. Shouldn't It work on both browsers.
Thanks in Advance.
BR,
Omprakash Limbhore

**Comment by mmanela** [comment]
@ostreifel  Can you look at this?

**Comment by ostreifel** [comment]
This would seem to be an issue with a specific version of ie11 as I am not able to repro this on my local computer's ie11, or the ie on the azure win10 & win8.1 vms I created.

Do you have any additional information that may help reproduce this issue?

**Comment by ostreifel** [comment]
Please refile if you find more information that may help resolve this issue.
