### ISSUE TITLE
When importing user story from excel and passed "Select all" option does not selecting any values and not displayed in multiple values fields area. 

### ISSUE THREAD

**Issue by rajeshksingh15** [Microsoft/vsts-extension-multivalue-control#68]
When importing user story from excel and passed "Select all"  value for multiple values fields .  It shows "Select all" itself instead of all values like iOS, Windows, Mac,

**Comment by mmanela** [comment]
@ostreifel  Can you take a look?

**Comment by ostreifel** [comment]
The behavior you are implying was never implemented is not supported.

If you want ios;windows;mac to be entered then that is the value you need to enter  - there is no translation logic.

**Comment by rajeshksingh15** [comment]
ok Thanks for an update @ostreifel ,  Is this consider as enhancement ? if yes then I can create user story to enhancement for this? please share your thought on this.

**Comment by ostreifel** [comment]
That process is not accessible to any form extensions logic as it done straight through client om calls - no chance for extensions confined to the browser to enhance the experience.

**Comment by rajeshksingh15** [comment]
ok Thank you for confirmation on this.
