### ISSUE TITLE
Any custom value get deleted when choose "Select all" option from multiple values fields for work item type User story

### ISSUE THREAD

**Issue by rajeshksingh15** [Microsoft/vsts-extension-multivalue-control#69]
Any custom value get deleted when choose "Select all" option from multiple values fields for work item type User story. And it displayed all default values setup.

**Comment by mmanela** [comment]
@ostreifel  Can you take a look?

**Comment by ostreifel** [comment]
Fixed, thank you for your report.

**Comment by rajeshksingh15** [comment]
Thanks for fixing the issue @ostreifel  , I guess code changes already push to production as part of "version": "2.0.20"?  Could you please confirm on this ?

**Comment by ostreifel** [comment]
Yes, .20 was the version that contained the fix

**Comment by rajeshksingh15** [comment]
Already verified and its worked. Thanks !
