### ISSUE TITLE
The input ID "Impacted Portfolio" does not exist in contribution 

### ISSUE THREAD

**Issue by PierreDony** [Microsoft/vsts-extension-multivalue-control#72]
VS403118: The input ID "Impacted Portfolio" does not exist in contribution "ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control"

**Comment by ostreifel** [comment]
It sounds like the label and the id have been [swapped](https://github.com/Microsoft/vsts-extension-multivalue-control/blob/master/xmldetails.md).

Make sure to use the id 
```
ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control
```

**Comment by PierreDony** [comment]
Customer tried  the solution  but I now is getting  a different error message.

VS403121: Extension(s) "ms-devlabs.vsts-extensions-multivalue-control.multivalue-form-control" does not exist , or has no work item form contribution.


Does he have to include page and group contribution as per:  https://docs.microsoft.com/en-us/azure/devops/extend/develop/configure-workitemform-extensions?view=vsts



Thanks,
Pierre
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ostreifel** [comment]
From the error message it sounds  like the contribution id is being used in place the the extension id

More details can be found [here](https://github.com/Microsoft/vsts-extension-multivalue-control/blob/master/xmldetails.md)

![image](https://user-images.githubusercontent.com/5203542/47745307-988a0580-dc40-11e8-9f51-d77b47ec3def.png)
