### ISSUE TITLE
MultiValue control

### ISSUE THREAD

**Issue by fred1n** [Microsoft/vsts-extension-multivalue-control#73]
When selecting multiple values...get a message at top indicating that the values field contains values that are not in the list of supported values.

The field type is Picklist String.  I can select a single value and it works fine but when another value is selected i get the message.

**Comment by ostreifel** [comment]
Please ensure that you have allowed users to input their own values in the field
![image](https://user-images.githubusercontent.com/5203542/46888242-c2f05c00-ce14-11e8-8ffa-91330ef03f99.png)
