### ISSUE TITLE
Multiple - Multivalue controls on local server version of TFS

### ISSUE THREAD

**Issue by gmanbadboy** [Microsoft/vsts-extension-multivalue-control#79]
I have got one multivalue control working.
How can i get 2 working in the same task template?
Thanks

**Comment by ostreifel** [comment]
It should be a repeat of the [procedure](https://github.com/Microsoft/vsts-extension-multivalue-control#how-to-get-started) you used to add the first one. Just make sure to use a different label, backing field and set of allowed values.
