### ISSUE TITLE
Works with TFS 2015 on-premise ?

### ISSUE THREAD

**Issue by sdgmits** [Microsoft/vsts-extension-multivalue-control#8]
Does this control work with TFS 2015 (Update 3) on-premise environment ?

**Comment by mmanela** [comment]
No, it will only work with TFS 2017.

**Comment by sdgmits** [comment]
ok, Thanks for the update.  So it will work in TFS 2017 online and hosted setup, both ?

**Comment by mmanela** [comment]
Yep, will work in both

**Comment by mmanela** [comment]
Yes
