### ISSUE TITLE
Not allowing to enter custom value and only showing values configured for the field

### ISSUE THREAD

**Issue by sujitks** [Microsoft/vsts-extension-multivalue-control#80]

**Comment by sujitks** [comment]
When I am configuring the custom control backed by 'Operating System' field which is a multi select string picklist, in the work item I can only see and select values configured for the field. When I click on the 'Add Item' it expands the control to select the existing value but no way to enter new value.


In other hand if I put the field 'Operating System' also in the layout it allows to enter values separated by the semi columns. In this case I get two fields in the Layout.

**Comment by mmanela** [comment]
The control today is designed to only let you pick from the existing list of configured values. The intent is that you update the list to add new values you want to support into it.

**Comment by ostreifel** [comment]
![image](https://user-images.githubusercontent.com/5203542/49184574-9cc74280-f314-11e8-9d99-c4ba345cb55e.png)
When checked and a search string that does not match any of the given options will presented as its own option.

ie if your options are
qwer
asdf
zxcv

and you search 
poiu

poiu will be presented as new option to select.
