### ISSUE TITLE
vsts-extension-multivalue-control and TE and MTM clients

### ISSUE THREAD

**Issue by t-anderson** [Microsoft/vsts-extension-multivalue-control#86]
How does the multivalue control field render on the form layout in the Visual Studio Team Explorer (TE) and Microsoft Test Manager (MTM) clients?

Our QA department would like to use this control to select multiple values in a field pick list in all clients, web, TE, MTM.  Can the multivalue control be extended to select multiple values in the TE and MTM clients?

**Comment by ostreifel** [comment]
This extension uses technologies provided by the web version of the work item form and is consequently limited to working in that environment.
