### ISSUE TITLE
Multi value fields don't load

### ISSUE THREAD

**Issue by duclm7** [Microsoft/vsts-extension-multivalue-control#89]
It has been working for last 6 months or more and today it suddenly stopped.
I have uninstalled and reinstalled with the latest version but still not working.
Can you please help? If you need more info, please let me know.

On premises installation
TFS version: 16.122.27102.1
Multi value control version: 2.2.22

Below is the error from Chrome's console log.

Content:17 Uncaught (in promise) Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (Content:17)
    at i (Content:17)
    at r (Content:14)
    at o (Content:17)
    at i (Content:17)
    at Object.instantiateChildren (Content:14)
    at h._reconcilerInstantiateChildren (Content:15)
    at h.mountChildren (Content:15)
    at h._createInitialChildren (Content:14)
    at h.mountComponent (Content:14)
r @ Content:17
i @ Content:17
r @ Content:14
o @ Content:17
i @ Content:17
instantiateChildren @ Content:14
_reconcilerInstantiateChildren @ Content:15
mountChildren @ Content:15
_createInitialChildren @ Content:14
mountComponent @ Content:14
mountComponent @ Content:16
mountChildren @ Content:15
_createInitialChildren @ Content:14
mountComponent @ Content:14
mountComponent @ Content:16
performInitialMount @ Content:14
mountComponent @ Content:14
mountComponent @ Content:16
performInitialMount @ Content:14
mountComponent @ Content:14
mountComponent @ Content:16
a @ Content:15
perform @ Content:17
s @ Content:15
perform @ Content:17
batchedUpdates @ Content:15
i @ Content:16
_renderNewRootComponent @ Content:15
_renderSubtreeIntoContainer @ Content:15
render @ Content:15
(anonymous) @ multivalue.js:16
(anonymous) @ multivalue.js:16
(anonymous) @ multivalue.js:16
s @ multivalue.js:16
Promise.then (async)
u @ multivalue.js:16
s @ multivalue.js:16
Promise.then (async)
u @ multivalue.js:16
(anonymous) @ multivalue.js:16
r @ multivalue.js:16
e.refresh @ multivalue.js:16
onLoaded @ multivalue.js:16
_proxyFunctions.(anonymous function) @ multivalue.html:11
f.invokeMethod @ multivalue.html:11
f.onMessage @ multivalue.html:11
e._handleMessageReceived @ multivalue.html:11
(anonymous) @ multivalue.html:11

**Comment by CopaDataPM** [comment]
ok, solution was to install 2.2.25 -> TFS 2017 seems to have issues to navigate to the correct market website (maybe because TFS has been renamend?). If somebody has issues that version 2.2.25 is not installed, uninstall the extension and navigate throuth "Browse Marketplace" to the new web site to get 2.2.25...

**Comment by ccrawford18** [comment]
I experienced the same issue with version 2.2.22 on TFS 2018 U2.  After upgrading to 2.2.25 as mentioned in the previous comment this has resolved my issue as well.

**Comment by ostreifel** [comment]
@duclm7  I created a 2017u3 testbox and installed the multivalue extension (2.2.25) to it without experiencing the issues described here.

This leads me to believe that this is the marketplace update glitch other users have reported and can be resolved as follows:

Try to install it from marketplace without uninstalling previous version. You'll get error, that extension already installed. But after that will be 2.2.25 version.

**Comment by duclm7** [comment]
> @duclm7 I created a 2017u3 testbox and installed the multivalue extension (2.2.25) to it without experiencing the issues described here.
> 
> This leads me to believe that this is the marketplace update glitch other users have reported and can be resolved as follows:
> 
> Try to install it from marketplace without uninstalling previous version. You'll get error, that extension already installed. But after that will be 2.2.25 version.

I tried that yesterday but it didn't work. Tried it again today and worked a treat.
Thanks guys.
