### ISSUE TITLE
Help Text not showing

### ISSUE THREAD

**Issue by ricardocovo** [Microsoft/vsts-extension-multivalue-control#9]
Hello,

I have the help text setup at my field level, but the control always shows the default description ("A work item form control which allows selection of multiple values.").

Is this a bug, or is there a different way to set HelpText for Contributions?

Thanks,

**Comment by kbalas** [comment]
@ricardocovo It is a bug if this is not displaying field help text. I created a tracking bug to my team and will work on it. Thanks for reporting. What version of the product are you using?

**Comment by ricardocovo** [comment]
@kbalas I am using TFS 2017; I updated the extension last week, so I must be on 1.0.2.

Thanks!

**Comment by MarkusLaakso** [comment]
Hello,

any update on this one? We have TFS2017.2 and recently installed vsts-extension-multivalue-control. This issue still exists.

--Markus

**Comment by mmanela** [comment]
We have a story on the backlog that will show the fields help text as long as you only bind your control to one field. Will this satisfy your need?

I will go bump up its priority if so.

**Comment by maxxxis** [comment]
I have the same issue. Your proposal sounds acceptable for now IMHO.

TIA!

**Comment by ostreifel** [comment]
This is now merged into the master branch of vsts
