### ISSUE TITLE
Possible to remove "Select All" or change functionality so it doesn't add all options?

### ISSUE THREAD

**Issue by nbdb** [Microsoft/vsts-extension-multivalue-control#97]
We have a pretty long picklist the runs up against the character limit if we use the Select All choice. If it were possible to have an option where "Select All" could be turned off, so we can replace it with the string "All" in the dropdown, it'd fix the problem for us.

**Comment by ostreifel** [comment]
Make sure you are using the multi line backing field. It will support up to [32k](https://social.msdn.microsoft.com/Forums/vstudio/en-US/b43d8dab-4ad1-4a36-a37d-fad9b57c0e48/work-item-fields-max-length) characters.

![image](https://user-images.githubusercontent.com/5203542/49821969-ab5c2380-fd30-11e8-9a0e-2d6577e558c9.png)

**Comment by nbdb** [comment]
Oh that works, thanks!

**Comment by ostreifel** [comment]
For future readers.

I ran some tests with the extension using 20 thousand options for the multivalue control. I think value limit for multi line fields has actually been raised well beyond 32k characters to the point that other issue take precedent well before the ability to save the work item (browser perf trying to load that many options, usibility of reading that many options etc.)
![image](https://user-images.githubusercontent.com/5203542/49823245-0fccb200-fd34-11e8-9252-e96c2e817e48.png)
Screen shot is using acceptance criteria as the backing field.
![image](https://user-images.githubusercontent.com/5203542/49823089-ba90a080-fd33-11e8-86cb-d793b8673eb0.png)

**Comment by VolicTV** [comment]
**I have 2 questions:**

1. For our use, we will never be using the "Select All" Field.  Is it possible to fully remove it? We are on TFS 2018 Update 3, so all XML based configurations. 
2. We have a selection called "No Business Priority" (use case scenario), I want to set it so that when that is selected, nothing else can be selected.
