### ISSUE TITLE
"Required" field indicator is displayed for multiple (all?) multi-value controls although it should be visible only for one

### ISSUE THREAD

**Issue by xymunter** [Microsoft/vsts-extension-multivalue-control#99]
TFS 2018.2
Multivalue control 2.2.25

I have a workitem type that contains two Multivalue controls.
One of the bound fields is configured to be set as _Required_ when the workitem is in the _Closed_ state (so this is defined in the _State_ tags, not in a _Transition_).

Here's what the configuration somewhat looks like:

![configuraiton](https://user-images.githubusercontent.com/46959331/51601384-7a146d00-1f04-11e9-8868-082347883112.png)

This works well, actually a little bit _too_ well: it seems as if all Multivalue controls are now being _Required_:

![required](https://user-images.githubusercontent.com/46959331/51600995-8d730880-1f03-11e9-9542-41edb70dfc67.png)

Now if the actually required Multivalue control gets selected, both indicator disappear:

![fixed](https://user-images.githubusercontent.com/46959331/51601037-ad0a3100-1f03-11e9-9e51-aba2c1cd24ac.png)

**Comment by mmanela** [comment]
@xymunter  Can you share your full xml file to I can test locally?

**Comment by joezha** [comment]
@xymunter I wasn't able to reproduce it locally and I tried the same set up as the xml you provided. Is it okay that we look at your repro via online screen sharing? Please feel free to reach out to me @ joezha@microsoft.com if you need further help.

**Comment by joezha** [comment]
@xymunter as we talked over skype, this is a UI bug in TFS 2018 and has been fixed in TFS 2019. The bug is that we will accidently identify them as the same field if they are using the same contribution.

**Comment by xymunter** [comment]
@joezha Thank you very much for your help. Really appreciate it.
